/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Coupon_Booster.php
*/
<?php
/**
 * Plugin Name: Affiliate Coupon Booster
 * Description: Aggregate and display affiliate coupons automatically tailored to your niche.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

class AffiliateCouponBooster {
    private $option_name = 'acb_saved_coupons';
    private $affiliate_id = 'your_affiliate_id'; // Replace with your affiliate ID

    public function __construct() {
        add_action('admin_menu', array($this, 'add_admin_menu'));
        add_action('admin_init', array($this, 'settings_init'));
        add_shortcode('affiliate_coupon_booster', array($this, 'render_coupons_shortcode'));
        add_action('acb_fetch_coupons_hook', array($this, 'fetch_and_store_coupons'));
        register_activation_hook(__FILE__, array($this, 'activate_plugin'));
        register_deactivation_hook(__FILE__, array($this, 'deactivate_plugin'));
    }

    public function add_admin_menu() {
        add_menu_page('Affiliate Coupon Booster', 'Affiliate Coupon Booster', 'manage_options', 'affiliate_coupon_booster', array($this, 'options_page'));
    }

    public function settings_init() {
        register_setting('acb_settings', 'acb_options');

        add_settings_section(
            'acb_section',
            __('Plugin Settings', 'acb'),
            null,
            'acb_settings'
        );

        add_settings_field(
            'acb_affiliate_id',
            __('Affiliate ID', 'acb'),
            array($this, 'affiliate_id_render'),
            'acb_settings',
            'acb_section'
        );

        add_settings_field(
            'acb_fetch_interval',
            __('Coupon Fetch Interval (hours)', 'acb'),
            array($this, 'fetch_interval_render'),
            'acb_settings',
            'acb_section'
        );

        add_settings_field(
            'acb_niche_keyword',
            __('Niche Keyword', 'acb'),
            array($this, 'niche_keyword_render'),
            'acb_settings',
            'acb_section'
        );
    }

    public function affiliate_id_render() {
        $options = get_option('acb_options');
        ?>
        <input type='text' name='acb_options[affiliate_id]' value='<?php echo isset($options['affiliate_id']) ? esc_attr($options['affiliate_id']) : ''; ?>' placeholder='your_affiliate_id'>
        <?php
    }

    public function fetch_interval_render() {
        $options = get_option('acb_options');
        $val = isset($options['fetch_interval']) ? intval($options['fetch_interval']) : 24;
        ?>
        <input type='number' min='1' max='168' name='acb_options[fetch_interval]' value='<?php echo $val; ?>' > (hours)
        <?php
    }

    public function niche_keyword_render() {
        $options = get_option('acb_options');
        ?>
        <input type='text' name='acb_options[niche_keyword]' value='<?php echo isset($options['niche_keyword']) ? esc_attr($options['niche_keyword']) : ''; ?>' placeholder='e.g., technology'>
        <?php
    }

    public function options_page() {
        ?>
        <form action='options.php' method='post'>
            <h2>Affiliate Coupon Booster Settings</h2>
            <?php
            settings_fields('acb_settings');
            do_settings_sections('acb_settings');
            submit_button();
            ?>
        </form>
        <p><strong>Usage:</strong> Insert shortcode <code>[affiliate_coupon_booster]</code> into any post or page to display coupons.</p>
        <?php
    }

    public function activate_plugin() {
        $options = get_option('acb_options');
        $interval_hours = isset($options['fetch_interval']) ? intval($options['fetch_interval']) : 24;
        if (!wp_next_scheduled('acb_fetch_coupons_hook')) {
            wp_schedule_event(time(), 'hourly', 'acb_fetch_coupons_hook');
        }
    }

    public function deactivate_plugin() {
        wp_clear_scheduled_hook('acb_fetch_coupons_hook');
    }

    // Example mock fetch function - replace with real API integration
    public function fetch_and_store_coupons() {
        $options = get_option('acb_options');
        $keyword = isset($options['niche_keyword']) ? sanitize_text_field($options['niche_keyword']) : '';
        $affiliate_id = isset($options['affiliate_id']) ? sanitize_text_field($options['affiliate_id']) : '';

        // Simulated coupon data fetched from an external source based on niche keyword
        $coupons = array(
            array(
                'title' => ucfirst($keyword) . ' 10% Off',
                'description' => 'Save 10% on all ' . $keyword . ' products.',
                'url' => 'https://affiliate.example.com/deal?affiliate=' . $affiliate_id . '&coupon=10off'
            ),
            array(
                'title' => ucfirst($keyword) . ' Free Shipping',
                'description' => 'Get free shipping on orders over $50.',
                'url' => 'https://affiliate.example.com/deal?affiliate=' . $affiliate_id . '&coupon=freeship'
            )
        );
        update_option($this->option_name, $coupons);
    }

    public function render_coupons_shortcode() {
        $coupons = get_option($this->option_name, array());
        if (empty($coupons)) {
            return '<p>No coupons available at the moment. Please check back later.</p>';
        }
        $html = '<div class="acb-coupons" style="border:1px solid #ccc;padding:10px;max-width:400px;">';
        $html .= '<h3>Latest Deals & Coupons</h3><ul style="list-style:none;padding-left:0;">';
        foreach ($coupons as $coupon) {
            $title = esc_html($coupon['title']);
            $desc = esc_html($coupon['description']);
            $url = esc_url($coupon['url']);
            $html .= "<li style='margin-bottom:10px;'><a href='$url' target='_blank' rel='nofollow noopener' style='font-weight:bold;color:#0073aa;'>$title</a><br/><small>$desc</small></li>";
        }
        $html .= '</ul></div>';
        return $html;
    }
}

new AffiliateCouponBooster();
