/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Deal_Booster.php
*/
<?php
/**
 * Plugin Name: Affiliate Deal Booster
 * Description: Curate and display affiliate coupons and deals with tracking to enhance affiliate revenue.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) exit;

class AffiliateDealBooster {
    private $option_name = 'adb_deals';
    private $affiliate_click_count_option = 'adb_clicks';

    public function __construct() {
        add_shortcode('affiliate_deals', [$this, 'render_deals']);
        add_action('wp_enqueue_scripts', [$this, 'enqueue_scripts']);
        add_action('wp_ajax_adb_track_click', [$this, 'ajax_track_click']);
        add_action('wp_ajax_nopriv_adb_track_click', [$this, 'ajax_track_click']);
        register_activation_hook(__FILE__, [$this, 'activation_hook']);
        register_deactivation_hook(__FILE__, [$this, 'deactivation_hook']);
    }

    public function activation_hook() {
        if (false === get_option($this->option_name)) {
            $default_deals = [
                [
                    'title' => 'Save 20% on Hosting at ExampleHost',
                    'url'   => 'https://affiliate.examplehost.com/?ref=yourid',
                    'code'  => 'SAVE20',
                    'expiry'=> '2026-12-31'
                ],
                [
                    'title' => '50% Off on WordPress Themes at ThemeStore',
                    'url'   => 'https://affiliate.themestore.com/deal?affiliate=yourid',
                    'code'  => '',
                    'expiry'=> '2026-06-30'
                ]
            ];
            update_option($this->option_name, $default_deals);
            update_option($this->affiliate_click_count_option, []);
        }
    }

    public function deactivation_hook() {
        // No data removal for safety
    }

    public function enqueue_scripts() {
        wp_enqueue_script('jquery');
        wp_enqueue_script('adb-script', plugin_dir_url(__FILE__) . 'adb-script.js', ['jquery'], '1.0', true);
        wp_localize_script('adb-script', 'adb_ajax', ['ajax_url' => admin_url('admin-ajax.php')]);
    }

    public function render_deals() {
        $deals = get_option($this->option_name, []);
        if(empty($deals)) {
            return '<p>No affiliate deals available currently.</p>';
        }
        $html = '<div class="adb-deals"><ul>'; 
        $now = date('Y-m-d');
        foreach($deals as $index => $deal) {
            if(isset($deal['expiry']) && $deal['expiry'] < $now) continue;
            $title = esc_html($deal['title']);
            $url = esc_url(add_query_arg(['adb_click' => $index], $deal['url']));
            $code = !empty($deal['code']) ? esc_html($deal['code']) : '';
            $html .= "<li><a href=\"$url\" class=\"adb-aff-link\" data-index=\"$index\" target=\"_blank\" rel=\"nofollow noopener\">$title</a>";
            if($code) {
                $html .= " <button class=\"adb-copy-code\" data-code=\"$code\">Copy Code</button>";
            }
            $html .= '</li>';
        }
        $html .= '</ul></div>';
        return $html;
    }

    public function ajax_track_click() {
        if (!isset($_POST['index']) || !is_numeric($_POST['index'])) {
            wp_send_json_error('Invalid data');
            wp_die();
        }
        $index = intval($_POST['index']);
        $clicks = get_option($this->affiliate_click_count_option, []);
        if (!isset($clicks[$index])) {
            $clicks[$index] = 0;
        }
        $clicks[$index]++;
        update_option($this->affiliate_click_count_option, $clicks);
        wp_send_json_success(['clicks' => $clicks[$index]]);
        wp_die();
    }
}

new AffiliateDealBooster();

/*
 * Below JavaScript code embedded via PHP for single-file plugin compliance
 */
add_action('wp_footer', function() {
    ?>
<script type="text/javascript">
jQuery(document).ready(function($){
    $('.adb-aff-link').click(function(e){
        var index = $(this).data('index');
        $.post(ajaxurl || adb_ajax.ajax_url, {
            action: 'adb_track_click',
            index: index
        });
    });

    $('.adb-copy-code').click(function(){
        var code = $(this).data('code');
        navigator.clipboard.writeText(code).then(function() {
            alert('Coupon code copied: ' + code);
        });
    });
});
</script>
    <?php
});