<?php
/*
Plugin Name: Affiliate Deal Booster
Plugin URI: https://example.com/affiliate-deal-booster
Description: Display exclusive affiliate coupon deals dynamically within relevant posts to increase conversions.
Version: 1.0
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Deal_Booster.php
License: GPL2
*/

if (!defined('ABSPATH')) exit; // Exit if accessed directly

class AffiliateDealBooster {

  public function __construct() {
    add_filter('the_content', array($this, 'inject_affiliate_deals'));
    add_action('admin_menu', array($this, 'add_admin_menu'));
    add_action('admin_init', array($this, 'settings_init'));
  }

  // Inject deals shortcode or autogenerated deals to content
  public function inject_affiliate_deals($content) {
    if(is_singular('post')) {
      $deals_html = get_option('adb_deals_html', '');
      if(!$deals_html) {
        $deals_html = '<div class="adb-deals" style="border:1px solid #ccc;padding:10px;margin:20px 0;background:#f9f9f9;">
          <strong>Exclusive Deals for You:</strong><ul>
          <li><a href="#" target="_blank">Save 20% on Widgets</a></li>
          <li><a href="#" target="_blank">Free Shipping on Orders $50+</a></li>
          <li><a href="#" target="_blank">Buy One Get One Free Offer</a></li>
          </ul></div>';
      }
      // Append deals block to content
      return $content . $deals_html;
    }
    return $content;
  }

  // Add Admin menu
  public function add_admin_menu() {
    add_options_page('Affiliate Deal Booster', 'Affiliate Deal Booster', 'manage_options', 'affiliate_deal_booster', array($this, 'options_page'));
  }

  // Register settings
  public function settings_init() {
    register_setting('adb_settings', 'adb_deals_html');
    add_settings_section('adb_section', 'Affiliate Deals Settings', null, 'affiliate_deal_booster');
    add_settings_field('adb_deals_html_field', 'Deals HTML', array($this, 'deals_html_render'), 'affiliate_deal_booster', 'adb_section');
  }

  // Settings field callback
  public function deals_html_render() {
    $value = get_option('adb_deals_html', '');
    echo '<textarea cols="60" rows="10" name="adb_deals_html" class="large-text code">' . esc_textarea($value) . '</textarea>';
    echo '<p class="description">Enter HTML for affiliate coupons and deals to display after post content. Use <a href="https://developer.wordpress.org/reference/functions/wp_kses_post/" target="_blank">allowed HTML</a>.</p>';
  }

  // Output admin options page
  public function options_page() {
    ?>
    <div class="wrap">
      <h1>Affiliate Deal Booster Settings</h1>
      <form action='options.php' method='post'>
        <?php
        settings_fields('adb_settings');
        do_settings_sections('affiliate_deal_booster');
        submit_button();
        ?>
      </form>
    </div>
    <?php
  }

}

new AffiliateDealBooster();
