/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Deal_Booster.php
*/
<?php
/**
 * Plugin Name: Affiliate Deal Booster
 * Description: Aggregates and displays personalized affiliate coupons and deals to increase conversion rates.
 * Version: 1.0
 * Author: Generated by AI
 * License: GPL2
 */

if(!defined('ABSPATH')) exit;

class AffiliateDealBooster {
    private $deals_option_key = 'adb_deals_data';

    public function __construct() {
        add_action('admin_menu', array($this, 'add_admin_menu'));
        add_action('admin_post_adb_save_deal', array($this, 'save_deal'));
        add_shortcode('aff_deals', array($this, 'display_deals_shortcode'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
    }

    public function add_admin_menu() {
        add_menu_page('Affiliate Deals', 'Affiliate Deal Booster', 'manage_options', 'affiliate-deal-booster', array($this, 'admin_page'), 'dashicons-tickets', 80);
    }

    public function admin_page() {
        if (!current_user_can('manage_options')) wp_die('Unauthorized');

        $deals = get_option($this->deals_option_key, array());
        ?>
        <div class="wrap">
            <h1>Affiliate Deal Booster - Manage Deals</h1>
            <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
                <input type="hidden" name="action" value="adb_save_deal">
                <?php wp_nonce_field('adb_save_deal_nonce', 'adb_nonce'); ?>
                <h2>Add New Deal</h2>
                <table class="form-table">
                    <tr><th scope="row"><label for="deal_title">Deal Title</label></th><td><input name="deal_title" type="text" id="deal_title" required class="regular-text"></td></tr>
                    <tr><th scope="row"><label for="deal_url">Affiliate URL</label></th><td><input name="deal_url" type="url" id="deal_url" required class="regular-text"></td></tr>
                    <tr><th scope="row"><label for="deal_code">Coupon Code</label></th><td><input name="deal_code" type="text" id="deal_code" class="regular-text"></td></tr>
                    <tr><th scope="row"><label for="deal_description">Description</label></th><td><textarea name="deal_description" id="deal_description" rows="4" class="large-text"></textarea></td></tr>
                    <tr><th scope="row">Categories (comma-separated)</th><td><input name="deal_categories" type="text" id="deal_categories" class="regular-text"></td></tr>
                    <tr><th scope="row">Expiry Date</th><td><input name="deal_expiry" type="date" id="deal_expiry"></td></tr>
                </table>
                <p><input type="submit" value="Add Deal" class="button button-primary"></p>
            </form>
            <hr>
            <h2>Existing Deals</h2>
            <?php if(empty($deals)): ?>
                <p>No deals added yet.</p>
            <?php else: ?>
                <table class="widefat striped">
                    <thead>
                        <tr><th>Title</th><th>URL</th><th>Coupon</th><th>Description</th><th>Categories</th><th>Expiry</th></tr>
                    </thead>
                    <tbody>
                    <?php foreach($deals as $deal): ?>
                        <tr>
                            <td><?php echo esc_html($deal['title']); ?></td>
                            <td><a href="<?php echo esc_url($deal['url']); ?>" target="_blank" rel="nofollow noopener noreferrer">Link</a></td>
                            <td><?php echo esc_html($deal['code']); ?></td>
                            <td><?php echo esc_html($deal['description']); ?></td>
                            <td><?php echo esc_html(implode(', ', $deal['categories'])); ?></td>
                            <td><?php echo esc_html($deal['expiry'] ? $deal['expiry'] : 'N/A'); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
        <?php
    }

    public function save_deal() {
        if(!current_user_can('manage_options')) wp_die('Unauthorized');
        check_admin_referer('adb_save_deal_nonce', 'adb_nonce');

        $title = sanitize_text_field($_POST['deal_title']);
        $url = esc_url_raw($_POST['deal_url']);
        $code = sanitize_text_field($_POST['deal_code']);
        $description = sanitize_textarea_field($_POST['deal_description']);
        $categories = array_filter(array_map('trim', explode(',', sanitize_text_field($_POST['deal_categories']))));
        $expiry = sanitize_text_field($_POST['deal_expiry']);

        $deals = get_option($this->deals_option_key, array());

        // Save new deal as associative array
        $deals[] = array(
            'title' => $title,
            'url' => $url,
            'code' => $code,
            'description' => $description,
            'categories' => $categories,
            'expiry' => $expiry,
        );

        update_option($this->deals_option_key, $deals);

        wp_redirect(admin_url('admin.php?page=affiliate-deal-booster&added=1'));
        exit;
    }

    public function display_deals_shortcode($atts) {
        $atts = shortcode_atts(array('category' => ''), $atts, 'aff_deals');

        $deals = get_option($this->deals_option_key, array());

        // Filter deals by category if provided
        if (!empty($atts['category'])) {
            $cat = strtolower(trim($atts['category']));
            $deals = array_filter($deals, function($deal) use ($cat) {
                return in_array($cat, array_map('strtolower', $deal['categories']));
            });
        }

        // Filter expired deals
        $today = date('Y-m-d');
        $deals = array_filter($deals, function($deal) use ($today) {
            return empty($deal['expiry']) || $deal['expiry'] >= $today;
        });

        if(empty($deals)) {
            return '<p>No deals available currently.</p>';
        }

        ob_start();
        echo '<div class="adb-deals-container" style="border:1px solid #ddd;padding:15px;background:#f9f9f9;">';
        foreach ($deals as $deal) {
            echo '<div class="adb-deal" style="margin-bottom:15px;">';
            echo '<h3 style="margin:0;"><a href="' . esc_url($deal['url']) . '" target="_blank" rel="nofollow noopener noreferrer">' . esc_html($deal['title']) . '</a></h3>';
            if (!empty($deal['code'])) {
                echo '<p><strong>Coupon Code:</strong> ' . esc_html($deal['code']) . '</p>';
            }
            if (!empty($deal['description'])) {
                echo '<p>' . esc_html($deal['description']) . '</p>';
            }
            if (!empty($deal['expiry'])) {
                echo '<p><em>Expires on: ' . esc_html($deal['expiry']) . '</em></p>';
            }
            echo '</div>';
        }
        echo '</div>';
        return ob_get_clean();
    }

    public function enqueue_scripts() {
        wp_enqueue_style('adb_styles', plugin_dir_url(__FILE__) . 'style.css');
    }
}

new AffiliateDealBooster();
