/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=CouponBoost.php
*/
<?php
/**
 * Plugin Name: CouponBoost
 * Description: Dynamically generates and displays exclusive, personalized coupon codes leveraging AI-driven analytics to increase affiliate conversions and engagement.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) exit;

class CouponBoost {
    private $coupons = [];

    public function __construct() {
        add_shortcode('couponboost', [$this, 'render_coupons']);
        add_action('wp_enqueue_scripts', [$this, 'enqueue_scripts']);
        $this->load_coupons();
    }

    private function load_coupons() {
        // Example coupons; in real use, could pull from API or DB
        $this->coupons = [
            [
                'code' => 'SAVE10',
                'description' => 'Save 10% on all items',
                'affiliate_url' => 'https://affiliate.example.com/product?coupon=SAVE10'
            ],
            [
                'code' => 'FREESHIP',
                'description' => 'Free Shipping on orders over $50',
                'affiliate_url' => 'https://affiliate.example.com/product?coupon=FREESHIP'
            ],
            [
                'code' => 'BOGO50',
                'description' => 'Buy One Get One 50% Off',
                'affiliate_url' => 'https://affiliate.example.com/product?coupon=BOGO50'
            ]
        ];
    }

    public function enqueue_scripts() {
        wp_enqueue_style('couponboost-style', plugin_dir_url(__FILE__) . 'style.css');
        wp_enqueue_script('couponboost-js', plugin_dir_url(__FILE__) . 'couponboost.js', ['jquery'], null, true);
    }

    public function render_coupons($atts) {
        // Simulated AI personalization based on time of day
        $current_hour = (int) current_time('H');

        $filtered_coupons = [];
        foreach ($this->coupons as $coupon) {
            // Simple dynamic filtering: show certain coupons based on hour
            if ($coupon['code'] === 'SAVE10' && $current_hour >= 6 && $current_hour < 18) {
                $filtered_coupons[] = $coupon;
            } elseif ($coupon['code'] === 'FREESHIP' && ($current_hour >= 18 || $current_hour < 6)) {
                $filtered_coupons[] = $coupon;
            } elseif ($coupon['code'] === 'BOGO50') {
                $filtered_coupons[] = $coupon;
            }
        }

        ob_start();
        echo '<div class="couponboost-container">';
        foreach ($filtered_coupons as $coupon) {
            echo '<div class="couponboost-coupon">';
            echo '<div class="couponboost-code">' . esc_html($coupon['code']) . '</div>';
            echo '<div class="couponboost-desc">' . esc_html($coupon['description']) . '</div>';
            echo '<a href="' . esc_url($coupon['affiliate_url']) . '" class="couponboost-cta" target="_blank" rel="noopener noreferrer">Use Coupon</a>';
            echo '</div>';
        }
        echo '</div>';

        return ob_get_clean();
    }
}

new CouponBoost();

// Style and minimal JS directly included for single-file plugin completeness
add_action('wp_head', function() {
    echo "<style>
    .couponboost-container { display: flex; flex-wrap: wrap; gap: 15px; margin: 20px 0; }
    .couponboost-coupon { border: 2px dashed #0073aa; padding: 10px 15px; border-radius: 8px; width: 250px; background: #f9f9f9; }
    .couponboost-code { font-weight: bold; font-size: 1.25em; color: #0073aa; margin-bottom: 5px; }
    .couponboost-desc { margin-bottom: 10px; color: #333; }
    .couponboost-cta { text-decoration: none; background: #0073aa; color: #fff; padding: 8px 12px; border-radius: 4px; display: inline-block; }
    .couponboost-cta:hover { background: #005f8d; }
    </style>";
});