/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Deal_Vault.php
*/
<?php
/**
 * Plugin Name: Affiliate Deal Vault
 * Description: Aggregate and display affiliate coupons/deals automatically to increase affiliate revenue.
 * Version: 1.0
 * Author: Generated by AI
 * License: GPLv2 or later
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

class AffiliateDealVault {
    private $deals_option_name = 'adv_cached_deals';
    private $affiliate_links = [
        // Example affiliate links with placeholders
        'amazon' => 'https://www.amazon.com/dp/%s?tag=youraffid-20',
        'ebay'   => 'https://www.ebay.com/itm/%s?campid=5337893504&customid=yourcustomid',
    ];

    public function __construct() {
        add_action('admin_menu', [$this, 'add_admin_menu']);
        add_action('admin_init', [$this, 'settings_init']);
        add_shortcode('affiliate_deals', [$this, 'render_deals_shortcode']);
        add_action('affiliate_deal_vault_cron', [$this, 'fetch_and_cache_deals']);

        // Schedule event on plugin activation & clear on deactivation
        register_activation_hook(__FILE__, [$this, 'activate_plugin']);
        register_deactivation_hook(__FILE__, [$this, 'deactivate_plugin']);
    }

    public function activate_plugin() {
        if (!wp_next_scheduled('affiliate_deal_vault_cron')) {
            wp_schedule_event(time(), 'hourly', 'affiliate_deal_vault_cron');
        }
    }

    public function deactivate_plugin() {
        $timestamp = wp_next_scheduled('affiliate_deal_vault_cron');
        if ($timestamp) {
            wp_unschedule_event($timestamp, 'affiliate_deal_vault_cron');
        }
    }

    public function add_admin_menu() {
        add_menu_page(
            'Affiliate Deal Vault',
            'Affiliate Deal Vault',
            'manage_options',
            'affiliate_deal_vault',
            [$this, 'admin_page'],
            'dashicons-megaphone',
            100
        );
    }

    public function settings_init() {
        register_setting('adv_settings', 'adv_api_keys');
        register_setting('adv_settings', 'adv_deal_sources');

        add_settings_section(
            'adv_settings_section',
            __('API and Source Settings', 'affiliate-deal-vault'),
            function() {
                echo '<p>'.__('Set your affiliate API keys and deal sources here.', 'affiliate-deal-vault').'</p>';
            },
            'affiliate_deal_vault'
        );

        add_settings_field(
            'adv_api_keys',
            __('Affiliate API Keys', 'affiliate-deal-vault'),
            function() {
                $options = get_option('adv_api_keys');
                echo '<input type="text" name="adv_api_keys[amazon]" placeholder="Amazon API Key" value="'.esc_attr(isset($options['amazon']) ? $options['amazon'] : '').'" size="40" />';
                echo '<br /><input type="text" name="adv_api_keys[ebay]" placeholder="eBay API Key" value="'.esc_attr(isset($options['ebay']) ? $options['ebay'] : '').'" size="40" />';
            },
            'affiliate_deal_vault',
            'adv_settings_section'
        );

        add_settings_field(
            'adv_deal_sources',
            __('Deal Sources', 'affiliate-deal-vault'),
            function() {
                $sources = get_option('adv_deal_sources', ['amazon', 'ebay']);
                echo '<label><input type="checkbox" name="adv_deal_sources[]" value="amazon"'.(in_array('amazon', $sources) ? ' checked' : '').' /> Amazon</label><br />';
                echo '<label><input type="checkbox" name="adv_deal_sources[]" value="ebay"'.(in_array('ebay', $sources) ? ' checked' : '').' /> eBay</label>';                
            },
            'affiliate_deal_vault',
            'adv_settings_section'
        );
    }

    public function admin_page() {
        ?>
        <div class="wrap">
            <h1>Affiliate Deal Vault Settings</h1>
            <form method="POST" action="options.php">
                <?php
                settings_fields('adv_settings');
                do_settings_sections('affiliate_deal_vault');
                submit_button();
                ?>
            </form>
            <h2>Cached Deals Preview</h2>
            <?php
            $deals = get_option($this->deals_option_name);
            if ($deals && is_array($deals)) {
                echo '<ul>';
                foreach ($deals as $deal) {
                    echo '<li><a href="'.esc_url($deal['url']).'" target="_blank">'.esc_html($deal['title']).'</a> - <strong>'.esc_html($deal['discount']).'</strong></li>';
                }
                echo '</ul>';
            } else {
                echo '<p>No deals cached yet. Run the cron or save settings to fetch deals.</p>';
            }
            ?>
        </div>
        <?php
    }

    public function fetch_and_cache_deals() {
        $sources = get_option('adv_deal_sources', ['amazon', 'ebay']);
        $all_deals = [];

        // Simulated fetching from affiliate APIs or RSS feeds
        foreach ($sources as $source) {
            if ($source === 'amazon') {
                $all_deals[] = [
                    'title' => 'Amazon Echo Dot - 30% Off',
                    'url' => sprintf($this->affiliate_links['amazon'], 'B07FZ8S74R'),
                    'discount' => '30% Off'
                ];
                $all_deals[] = [
                    'title' => 'Kindle Paperwhite 25% Discount',
                    'url' => sprintf($this->affiliate_links['amazon'], 'B08N36XNTT'),
                    'discount' => '25% Off'
                ];
            }
            if ($source === 'ebay') {
                $all_deals[] = [
                    'title' => 'Refurbished MacBook Pro 15% Off',
                    'url' => sprintf($this->affiliate_links['ebay'], '123456789012'),
                    'discount' => '15% Off'
                ];
            }
        }

        update_option($this->deals_option_name, $all_deals);
    }

    public function render_deals_shortcode($atts) {
        $deals = get_option($this->deals_option_name, []);
        if (empty($deals)) {
            return '<p>No deals available right now. Please check back soon.</p>';
        }

        $output = '<div class="affiliate-deal-vault"><ul>';
        foreach ($deals as $deal) {
            $output .= sprintf(
                '<li><a href="%s" target="_blank" rel="nofollow noopener">%s</a> - <strong>%s</strong></li>',
                esc_url($deal['url']),
                esc_html($deal['title']),
                esc_html($deal['discount'])
            );
        }
        $output .= '</ul></div>';
        return $output;
    }
}

new AffiliateDealVault();
