/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Deal_Vault.php
*/
<?php
/**
 * Plugin Name: Affiliate Deal Vault
 * Description: Easily create, manage, and display affiliate coupons and deals with tracking and scheduling.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

class Affiliate_Deal_Vault {

    public function __construct() {
        add_action('init', array($this, 'register_deal_post_type'));
        add_action('add_meta_boxes', array($this, 'add_deal_meta_boxes'));
        add_action('save_post', array($this, 'save_deal_meta'), 10, 2);

        add_shortcode('affiliate_deals', array($this, 'render_deals_shortcode'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));

        add_action('template_redirect', array($this, 'redirect_affiliate_link'));
    }

    public function register_deal_post_type() {
        $labels = array(
            'name' => 'Affiliate Deals',
            'singular_name' => 'Affiliate Deal',
            'add_new' => 'Add New Deal',
            'add_new_item' => 'Add New Affiliate Deal',
            'edit_item' => 'Edit Deal',
            'new_item' => 'New Deal',
            'view_item' => 'View Deal',
            'search_items' => 'Search Deals',
            'not_found' => 'No Deals found',
            'not_found_in_trash' => 'No Deals found in Trash',
        );
        $args = array(
            'labels' => $labels,
            'public' => true,
            'has_archive' => true,
            'rewrite' => array('slug' => 'affiliate-deals'),
            'supports' => array('title', 'editor'),
            'show_in_rest' => true,
        );
        register_post_type('affiliate_deal', $args);
    }

    public function add_deal_meta_boxes() {
        add_meta_box('deal_details', 'Deal Details', array($this, 'render_deal_meta_box'), 'affiliate_deal', 'normal', 'high');
    }

    public function render_deal_meta_box($post) {
        wp_nonce_field('save_deal_meta', 'deal_meta_nonce');

        $affiliate_url = get_post_meta($post->ID, '_affiliate_url', true);
        $coupon_code = get_post_meta($post->ID, '_coupon_code', true);
        $expiry_date = get_post_meta($post->ID, '_expiry_date', true);
        $is_active = get_post_meta($post->ID, '_is_active', true);

        ?>
        <p>
            <label for="affiliate_url">Affiliate URL (required):</label><br>
            <input type="url" id="affiliate_url" name="affiliate_url" value="<?php echo esc_attr($affiliate_url); ?>" style="width:100%;" required>
        </p>
        <p>
            <label for="coupon_code">Coupon Code (optional):</label><br>
            <input type="text" id="coupon_code" name="coupon_code" value="<?php echo esc_attr($coupon_code); ?>" style="width:50%;">
        </p>
        <p>
            <label for="expiry_date">Expiry Date (YYYY-MM-DD, optional):</label><br>
            <input type="date" id="expiry_date" name="expiry_date" value="<?php echo esc_attr($expiry_date); ?>">
        </p>
        <p>
            <label for="is_active">
                <input type="checkbox" id="is_active" name="is_active" value="1" <?php checked($is_active, '1'); ?>> Active
            </label>
        </p>
        <?php
    }

    public function save_deal_meta($post_id, $post) {
        if (!isset($_POST['deal_meta_nonce']) || !wp_verify_nonce($_POST['deal_meta_nonce'], 'save_deal_meta')) {
            return $post_id;
        }

        if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
            return $post_id;
        }

        if ('affiliate_deal' !== $post->post_type) {
            return $post_id;
        }

        if (!current_user_can('edit_post', $post_id)) {
            return $post_id;
        }

        $affiliate_url = isset($_POST['affiliate_url']) ? esc_url_raw($_POST['affiliate_url']) : '';
        $coupon_code = isset($_POST['coupon_code']) ? sanitize_text_field($_POST['coupon_code']) : '';
        $expiry_date = isset($_POST['expiry_date']) ? sanitize_text_field($_POST['expiry_date']) : '';
        $is_active = isset($_POST['is_active']) ? '1' : '0';

        update_post_meta($post_id, '_affiliate_url', $affiliate_url);
        update_post_meta($post_id, '_coupon_code', $coupon_code);
        update_post_meta($post_id, '_expiry_date', $expiry_date);
        update_post_meta($post_id, '_is_active', $is_active);
    }

    public function enqueue_scripts() {
        wp_enqueue_style('affiliate-deal-vault-style', plugins_url('style.css', __FILE__));
    }

    public function render_deals_shortcode($atts) {
        $today = date('Y-m-d');

        $args = array(
            'post_type' => 'affiliate_deal',
            'posts_per_page' => -1,
            'meta_query' => array(
                array(
                    'key' => '_is_active',
                    'value' => '1',
                    'compare' => '=',
                ),
                array(
                    'relation' => 'OR',
                    array(
                        'key' => '_expiry_date',
                        'value' => '',
                        'compare' => '=' // no expiry
                    ),
                    array(
                        'key' => '_expiry_date',
                        'value' => $today,
                        'compare' => '>=',
                        'type' => 'DATE'
                    )
                )
            ),
            'orderby' => 'date',
            'order' => 'DESC',
        );

        $deals = new WP_Query($args);

        if (!$deals->have_posts()) {
            return '<p>No active deals at the moment. Please check back later.</p>';
        }

        $output = '<div class="affiliate-deals-container">';

        while ($deals->have_posts()) {
            $deals->the_post();
            $deal_id = get_the_ID();
            $title = get_the_title();
            $description = get_the_content();
            $coupon_code = get_post_meta($deal_id, '_coupon_code', true);

            $output .= '<div class="affiliate-deal-item">';
            $output .= '<h3>' . esc_html($title) . '</h3>';
            $output .= '<p>' . wp_kses_post(wp_trim_words($description, 30, '...')) . '</p>';

            if ($coupon_code) {
                $output .= '<p><strong>Coupon Code:</strong> <span class="coupon-code" style="font-family: monospace; background: #eef; padding: 3px 6px;">' . esc_html($coupon_code) . '</span> <button class="copy-coupon-button" data-clipboard-text="' . esc_attr($coupon_code) . '">Copy</button></p>';
            }

            $output .= '<p><a href="' . esc_url(add_query_arg('deal_id', $deal_id, home_url('/'))) . '" class="affiliate-visit-button" target="_blank" rel="nofollow noopener">Use Deal</a></p>';
            $output .= '</div>';
        }

        $output .= '</div>';

        // Include minimal inline JS for copy to clipboard
        $output .= "<script>document.addEventListener('click', function(e) {if (e.target.classList.contains('copy-coupon-button')) {var text = e.target.getAttribute('data-clipboard-text');navigator.clipboard.writeText(text).then(function() {e.target.innerText = 'Copied';setTimeout(function() {e.target.innerText = 'Copy';}, 2000);});}}, false);</script>";

        wp_reset_postdata();

        return $output;
    }

    public function redirect_affiliate_link() {
        if (is_singular('affiliate_deal') && isset($_GET['redirect'])) {
            $post_id = get_the_ID();
            $url = get_post_meta($post_id, '_affiliate_url', true);
            if ($url) {
                wp_redirect($url);
                exit;
            }
        }

        if (isset($_GET['deal_id'])) {
            $deal_id = intval($_GET['deal_id']);
            $url = get_post_meta($deal_id, '_affiliate_url', true);
            if ($url) {
                // Track click count
                $clicks = get_post_meta($deal_id, '_click_count', true);
                $clicks = $clicks ? intval($clicks) + 1 : 1;
                update_post_meta($deal_id, '_click_count', $clicks);

                wp_redirect($url);
                exit;
            }
        }
    }

}

new Affiliate_Deal_Vault();
