/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=AI_Affiliate_Coupon_Generator.php
*/
<?php
/**
 * Plugin Name: AI Affiliate Coupon Generator
 * Plugin URI: https://example.com/ai-affiliate-coupon
 * Description: Automatically generates and displays personalized affiliate coupons using AI to boost your commissions.
 * Version: 1.0.0
 * Author: Your Name
 * License: GPL v2 or later
 */

if (!defined('ABSPATH')) {
    exit;
}

class AI_Affiliate_Coupon_Generator {
    public function __construct() {
        add_action('init', array($this, 'init'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_shortcode('ai_coupon_generator', array($this, 'coupon_shortcode'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_action('wp_ajax_generate_coupon', array($this, 'ajax_generate_coupon'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        if (get_option('ai_coupon_pro') !== 'yes') {
            add_action('admin_notices', array($this, 'pro_notice'));
        }
    }

    public function enqueue_scripts() {
        wp_enqueue_script('ai-coupon-js', plugin_dir_url(__FILE__) . 'ai-coupon.js', array('jquery'), '1.0.0', true);
        wp_localize_script('ai-coupon-js', 'ajax_object', array('ajax_url' => admin_url('admin-ajax.php')));
    }

    public function coupon_shortcode($atts) {
        $atts = shortcode_atts(array(
            'niche' => 'general',
            'affiliate' => 'amazon'
        ), $atts);

        ob_start();
        ?>
        <div id="ai-coupon-container" data-niche="<?php echo esc_attr($atts['niche']); ?>" data-affiliate="<?php echo esc_attr($atts['affiliate']); ?>">
            <button id="generate-coupon" class="button">Generate Coupon</button>
            <div id="coupon-result"></div>
        </div>
        <?php
        return ob_get_clean();
    }

    public function ajax_generate_coupon() {
        if (!wp_verify_nonce($_POST['nonce'], 'ai_coupon_nonce')) {
            wp_die('Security check failed');
        }

        $niche = sanitize_text_field($_POST['niche']);
        $affiliate = sanitize_text_field($_POST['affiliate']);

        // Simple AI simulation (Pro version would integrate real AI API like OpenAI)
        $coupons = array(
            'amazon' => array(
                'general' => 'SAVE20% - Amazon Exclusive Deal!',
                'tech' => 'TECH15 - 15% off Electronics',
                'fashion' => 'FASHION25 - 25% off Clothing'
            ),
            'other' => array(
                'general' => 'AFF20 - 20% Off Any Purchase',
                'tech' => 'GADGET10 - $10 off Gadgets'
            )
        );

        $free_limit = get_option('ai_coupon_generated', 0);
        if ($free_limit >= 5 && get_option('ai_coupon_pro') !== 'yes') {
            wp_send_json_error('Upgrade to Pro for unlimited coupons!');
        }

        $coupon = isset($coupons[$affiliate][$niche]) ? $coupons[$affiliate][$niche] : 'SAVE10% - Affiliate Deal!';
        $aff_link = 'https://youraffiliate.link/?coupon=' . urlencode($coupon);

        update_option('ai_coupon_generated', $free_limit + 1);

        ob_start();
        ?>
        <div class="ai-coupon">
            <h3><?php echo esc_html($coupon); ?></h3>
            <a href="<?php echo esc_url($aff_link); ?}" target="_blank" class="coupon-button">Claim Deal (Affiliate Link)</a>
            <p>Generated by AI Affiliate Coupon Generator</p>
        </div>
        <style>
        .ai-coupon { border: 2px dashed #0073aa; padding: 20px; margin: 10px 0; background: #f9f9f9; }
        .coupon-button { background: #0073aa; color: white; padding: 10px 20px; text-decoration: none; display: inline-block; }
        </style>
        <?php
        wp_send_json_success(ob_get_clean());
    }

    public function admin_menu() {
        add_options_page('AI Coupon Settings', 'AI Coupons', 'manage_options', 'ai-coupon', array($this, 'settings_page'));
    }

    public function settings_page() {
        if (isset($_POST['ai_coupon_pro'])) {
            update_option('ai_coupon_pro', 'yes');
            echo '<div class="notice notice-success"><p>Pro activated! (Demo)</p></div>';
        }
        ?>
        <div class="wrap">
            <h1>AI Affiliate Coupon Generator Settings</h1>
            <form method="post">
                <?php wp_nonce_field('ai_coupon_settings'); ?>
                <p><input type="submit" name="ai_coupon_pro" class="button-primary" value="Activate Pro (Demo)" /></p>
                <p>Free limit: <?php echo get_option('ai_coupon_generated', 0); ?>/5</p>
            </form>
        </div>
        <?php
    }

    public function pro_notice() {
        echo '<div class="notice notice-info"><p><strong>AI Affiliate Coupon:</strong> Upgrade to Pro for unlimited generations and advanced AI!</p></div>';
    }

    public function activate() {
        update_option('ai_coupon_generated', 0);
    }
}

new AI_Affiliate_Coupon_Generator();

// Frontend JS (embedded for single file)
function ai_coupon_add_js() {
    if (!wp_script_is('ai-coupon-js', 'enqueued')) return;
    ?>
    <script>
    jQuery(document).ready(function($) {
        $('#generate-coupon').click(function() {
            var container = $('#ai-coupon-container');
            $.post(ajax_object.ajax_url, {
                action: 'generate_coupon',
                niche: container.data('niche'),
                affiliate: container.data('affiliate'),
                nonce: '<?php echo wp_create_nonce("ai_coupon_nonce"); ?>'
            }, function(response) {
                if (response.success) {
                    $('#coupon-result').html(response.data);
                } else {
                    alert(response.data);
                }
            });
        });
    });
    </script>
    <?php
}
add_action('wp_footer', 'ai_coupon_add_js');