/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=GeoAffiliate_Pro.php
*/
<?php
/**
 * Plugin Name: GeoAffiliate Pro
 * Description: Manage affiliate links with geolocation targeting, automatic insertion, and scheduling.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) { exit; }

class GeoAffiliatePro {
    private $affiliate_links = [];
    private $geo_data = [];

    public function __construct() {
        add_action('wp_head', [$this, 'insert_affiliate_links']);
        add_shortcode('geoaffiliate', [$this, 'geoaffiliate_shortcode']);
        add_action('wp_enqueue_scripts', [$this, 'enqueue_scripts']);
        add_action('init', [$this, 'maybe_track_click']);
        $this->load_links();
    }

    private function load_links() {
        // Example affiliate links setup. In real plugin, admin interface would manage these links.
        $this->affiliate_links = [
            'global' => 'https://example.com/global-affiliate',
            'US' => 'https://example.com/us-affiliate',
            'FR' => 'https://example.com/fr-affiliate',
            'IN' => 'https://example.com/in-affiliate'
        ];

        // Example schedule for link activation (Y-m-d H:i)
        // Only links active within schedule will appear, others fallback to global
        $this->link_schedules = [
            'US' => ['start' => '2025-12-01 00:00', 'end' => '2025-12-31 23:59'],
            'FR' => ['start' => '2025-12-10 00:00', 'end' => '2025-12-20 23:59'],
        ];
    }

    private function get_visitor_country() {
        if (isset($_SERVER['HTTP_CF_IPCOUNTRY'])) { // Cloudflare
            return $_SERVER['HTTP_CF_IPCOUNTRY'];
        }
        // Fallback: use IP Geolocation API (free) - limited or blocked in environments
        $ip = $_SERVER['REMOTE_ADDR'] ?? '';
        if (filter_var($ip, FILTER_VALIDATE_IP)) {
            $response = wp_remote_get('https://ipapi.co/' . $ip . '/country/');
            if (!is_wp_error($response) && wp_remote_retrieve_response_code($response) == 200) {
                return trim(wp_remote_retrieve_body($response));
            }
        }
        return 'global';
    }

    private function is_link_active($country_code) {
        if (!isset($this->link_schedules[$country_code])) {
            return true; // no schedule, always active
        }
        $now = new DateTime('now', new DateTimeZone('UTC'));
        $start = DateTime::createFromFormat('Y-m-d H:i', $this->link_schedules[$country_code]['start'], new DateTimeZone('UTC'));
        $end = DateTime::createFromFormat('Y-m-d H:i', $this->link_schedules[$country_code]['end'], new DateTimeZone('UTC'));
        return ($now >= $start && $now <= $end);
    }

    public function insert_affiliate_links() {
        $country = $this->get_visitor_country();
        $link = $this->affiliate_links[$country] ?? $this->affiliate_links['global'];
        if (!$this->is_link_active($country)) {
            $link = $this->affiliate_links['global'];
        }
        // Insert JS that replaces placeholder links automatically
        ?>
        <script>
        document.addEventListener('DOMContentLoaded', function() {
            var links = document.querySelectorAll('a.geoaffiliate');
            links.forEach(function(a) {
                a.href = '<?php echo esc_js($link); ?>';
                a.setAttribute('target', '_blank');
                a.setAttribute('rel', 'noopener noreferrer');
            });
        });
        </script>
        <?php
    }

    public function geoaffiliate_shortcode($atts) {
        $atts = shortcode_atts(['text' => 'Affiliate Link'], $atts);
        // Outputs an anchor tag with class to be replaced
        return '<a href="#" class="geoaffiliate">' . esc_html($atts['text']) . '</a>';
    }

    public function enqueue_scripts() {
        // Placeholder for future enhancements
    }

    public function maybe_track_click() {
        if (isset($_GET['geoaffiliate_click'])) {
            // Minimal click tracking without DB: log file
            $ip = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
            $country = $this->get_visitor_country();
            $link = sanitize_text_field($_GET['geoaffiliate_click']);
            $log_line = date('Y-m-d H:i:s') . "," . $ip . "," . $country . "," . $link . "\n";
            @file_put_contents(plugin_dir_path(__FILE__) . 'click_log.csv', $log_line, FILE_APPEND | LOCK_EX);
            // Redirect to link
            wp_redirect($link);
            exit;
        }
    }
}

new GeoAffiliatePro();
