/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Booster_Pro.php
*/
<?php
/**
 * Plugin Name: Affiliate Booster Pro
 * Description: Automatically detect product mentions and insert affiliate links with live coupons to boost affiliate revenue.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) die('Direct access not allowed');

class AffiliateBoosterPro {
    private $affiliate_networks = array(
        'example_affiliate' => array(
            'name' => 'Example Affiliate',
            'base_url' => 'https://affiliate.example.com/product/',
            'coupon_api' => 'https://affiliate.example.com/api/coupons?product=',
            'affiliate_id' => 'AFFILIATE123'
        )
    );

    private $product_keywords = array(
        'widget',
        'gadget',
        'tool',
        'device'
    );

    public function __construct() {
        add_filter('the_content', array($this, 'process_content'));
        add_action('admin_menu', array($this, 'add_admin_menu'));
        add_action('admin_init', array($this, 'settings_init'));
    }

    public function process_content($content) {
        foreach ($this->product_keywords as $keyword) {
            if (stripos($content, $keyword) !== false) {
                $link = $this->generate_affiliate_link($keyword);
                $coupon = $this->fetch_coupon($keyword);
                $replacement = $keyword;
                if ($link) {
                    $replacement = '<a href="' . esc_url($link) . '" target="_blank" rel="nofollow">' . esc_html($keyword) . '</a>';
                    if ($coupon) {
                        $replacement .= ' <span style="color:#d9534f; font-weight:bold;">(' . esc_html($coupon) . ')</span>';
                    }
                }
                $content = preg_replace('/\b' . preg_quote($keyword, '/') . '\b/i', $replacement, $content, 1);
            }
        }
        return $content;
    }

    private function generate_affiliate_link($product) {
        $network = $this->affiliate_networks['example_affiliate'];
        $slug = sanitize_title($product);
        $url = $network['base_url'] . $slug;
        $url = add_query_arg('aff_id', $network['affiliate_id'], $url);
        return $url;
    }

    private function fetch_coupon($product) {
        $network = $this->affiliate_networks['example_affiliate'];
        $api_url = $network['coupon_api'] . urlencode($product);

        $response = wp_remote_get($api_url);
        if (is_wp_error($response)) return '';

        $body = wp_remote_retrieve_body($response);
        $data = json_decode($body, true);

        if (isset($data['coupon'])) {
            return $data['coupon'];
        }
        return '';
    }

    public function add_admin_menu() {
        add_options_page('Affiliate Booster Pro', 'Affiliate Booster Pro', 'manage_options', 'affiliate-booster-pro', array($this, 'options_page'));
    }

    public function settings_init() {
        register_setting('affiliateBoosterPro', 'affiliateBoosterPro_settings');

        add_settings_section(
            'affiliateBoosterPro_section',
            __('Settings for Affiliate Booster Pro', 'affiliateBoosterPro'),
            null,
            'affiliateBoosterPro'
        );

        add_settings_field(
            'affiliateBoosterPro_keywords',
            __('Product Keywords', 'affiliateBoosterPro'),
            array($this, 'keywords_render'),
            'affiliateBoosterPro',
            'affiliateBoosterPro_section'
        );
    }

    public function keywords_render() {
        $options = get_option('affiliateBoosterPro_settings');
        $keywords = isset($options['keywords']) ? esc_attr($options['keywords']) : implode(', ', $this->product_keywords);
        echo "<input type='text' name='affiliateBoosterPro_settings[keywords]' value='$keywords' style='width: 100%;' />";
        echo "<p class='description'>Enter product keywords separated by commas. The plugin will look for these words to add affiliate links.</p>";
    }

    public function options_page() {
        ?>
        <form action='options.php' method='post'>
            <h2>Affiliate Booster Pro Settings</h2>
            <?php
            settings_fields('affiliateBoosterPro');
            do_settings_sections('affiliateBoosterPro');
            submit_button();
            ?>
        </form>
        <?php
    }
}

new AffiliateBoosterPro();
