/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Coupons___Deals_Manager.php
*/
<?php
/**
 * Plugin Name: Affiliate Coupons & Deals Manager
 * Description: Easily create, display, and manage affiliate coupons and deals with shortcode and widget support.
 * Version: 1.0
 * Author: Generated by AI
 * License: GPLv2 or later
 */

if (!defined('ABSPATH')) exit;

class Affiliate_Coupons_Deals {

    public function __construct() {
        add_action('init', array($this, 'register_coupon_post_type'));
        add_action('add_meta_boxes', array($this, 'add_coupon_meta_boxes'));
        add_action('save_post', array($this, 'save_coupon_meta')); 
        add_shortcode('affiliate_coupons', array($this, 'render_coupons_shortcode'));
        add_action('widgets_init', function() {
            register_widget('Affiliate_Coupons_Widget');
        });
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
    }

    public function enqueue_scripts() {
        wp_enqueue_style('acdm-style', plugins_url('style.css', __FILE__));
    }

    public function register_coupon_post_type() {
        $labels = array(
            'name'               => __('Coupons & Deals', 'acdm'),
            'singular_name'      => __('Coupon / Deal', 'acdm'),
            'add_new_item'       => __('Add New Coupon/Deal', 'acdm'),
            'edit_item'          => __('Edit Coupon/Deal', 'acdm'),
            'new_item'           => __('New Coupon/Deal', 'acdm'),
            'view_item'          => __('View Coupon/Deal', 'acdm'),
            'search_items'       => __('Search Coupons/Deals', 'acdm'),
            'not_found'          => __('No Coupons/Deals found', 'acdm'),
            'not_found_in_trash' => __('No Coupons/Deals found in Trash', 'acdm'),
            'menu_name'          => __('Affiliate Coupons', 'acdm')
        );

        $args = array(
            'labels'             => $labels,
            'public'             => false,
            'show_ui'            => true,
            'show_in_menu'       => true,
            'capability_type'    => 'post',
            'supports'           => array('title','editor'),
            'menu_icon'          => 'dashicons-tag',
            'has_archive'        => false
        );

        register_post_type('acdm_coupon', $args);
    }

    public function add_coupon_meta_boxes() {
        add_meta_box(
            'acdm_coupon_details',
            __('Coupon/Deal Details', 'acdm'),
            array($this, 'coupon_meta_box_callback'),
            'acdm_coupon',
            'normal',
            'high'
        );
    }

    public function coupon_meta_box_callback($post) {
        wp_nonce_field('acdm_save_coupon_meta', 'acdm_coupon_meta_nonce');

        $affiliate_url = get_post_meta($post->ID, '_acdm_affiliate_url', true);
        $discount_code = get_post_meta($post->ID, '_acdm_discount_code', true);
        $expiry_date = get_post_meta($post->ID, '_acdm_expiry_date', true);
        $is_active = get_post_meta($post->ID, '_acdm_is_active', true);

        echo '<p><label for="acdm_affiliate_url">Affiliate Link URL:</label><br />';
        echo '<input type="url" id="acdm_affiliate_url" name="acdm_affiliate_url" value="'.esc_attr($affiliate_url).'" style="width:100%;" required /></p>';

        echo '<p><label for="acdm_discount_code">Discount Code (optional):</label><br />';
        echo '<input type="text" id="acdm_discount_code" name="acdm_discount_code" value="'.esc_attr($discount_code).'" style="width:100%;" /></p>';

        echo '<p><label for="acdm_expiry_date">Expiry Date (YYYY-MM-DD, optional):</label><br />';
        echo '<input type="date" id="acdm_expiry_date" name="acdm_expiry_date" value="'.esc_attr($expiry_date).'" /></p>';

        echo '<p><label><input type="checkbox" id="acdm_is_active" name="acdm_is_active" '.checked($is_active, 'yes', false).' /> Active</label></p>';
    }

    public function save_coupon_meta($post_id) {
        if (!isset($_POST['acdm_coupon_meta_nonce']) || !wp_verify_nonce($_POST['acdm_coupon_meta_nonce'], 'acdm_save_coupon_meta')) {
            return;
        }

        if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) return;

        if (!current_user_can('edit_post', $post_id)) return;

        if (isset($_POST['acdm_affiliate_url'])) {
            update_post_meta($post_id, '_acdm_affiliate_url', esc_url_raw($_POST['acdm_affiliate_url']));
        }

        if (isset($_POST['acdm_discount_code'])) {
            update_post_meta($post_id, '_acdm_discount_code', sanitize_text_field($_POST['acdm_discount_code']));
        } else {
            delete_post_meta($post_id, '_acdm_discount_code');
        }

        if (isset($_POST['acdm_expiry_date'])) {
            update_post_meta($post_id, '_acdm_expiry_date', sanitize_text_field($_POST['acdm_expiry_date']));
        } else {
            delete_post_meta($post_id, '_acdm_expiry_date');
        }

        $active = (isset($_POST['acdm_is_active']) && $_POST['acdm_is_active'] === 'on') ? 'yes' : 'no';
        update_post_meta($post_id, '_acdm_is_active', $active);
    }

    public function render_coupons_shortcode($atts) {
        $atts = shortcode_atts(array(
            'count' => 5
        ), $atts, 'affiliate_coupons');

        $query = new WP_Query(array(
            'post_type' => 'acdm_coupon',
            'posts_per_page' => intval($atts['count']),
            'meta_key' => '_acdm_is_active',
            'meta_value' => 'yes'
        ));

        if (!$query->have_posts()) {
            return '<p>No coupons or deals available at the moment.</p>';
        }

        ob_start();
        echo '<div class="acdm-coupons-list">';
        while ($query->have_posts()) {
            $query->the_post();
            $affiliate_url = esc_url(get_post_meta(get_the_ID(), '_acdm_affiliate_url', true));
            $discount_code = esc_html(get_post_meta(get_the_ID(), '_acdm_discount_code', true));
            $expiry_date = get_post_meta(get_the_ID(), '_acdm_expiry_date', true);

            // Check expiry date
            $expired = false;
            if ($expiry_date && strtotime($expiry_date) < time()) {
                $expired = true;
            }

            if ($expired) continue;

            echo '<div class="acdm-coupon">';
            echo '<h3 class="acdm-coupon-title">' . get_the_title() . '</h3>';
            echo '<div class="acdm-coupon-content">' . get_the_content() . '</div>';

            if ($discount_code) {
                echo '<p><strong>Use Code:</strong> <span class="acdm-discount-code">' . $discount_code . '</span></p>';
            }

            echo '<p><a class="acdm-apply-button" href="' . $affiliate_url . '" target="_blank" rel="nofollow noopener noreferrer">Redeem Offer</a></p>';
            echo '</div>';
        }
        echo '</div>';

        wp_reset_postdata();

        return ob_get_clean();
    }
}

class Affiliate_Coupons_Widget extends WP_Widget {
    public function __construct() {
        parent::__construct(
            'affiliate_coupons_widget', 
            __('Affiliate Coupons & Deals', 'acdm'), 
            array('description' => __('Display latest active affiliate coupons and deals', 'acdm'))
        );
    }

    public function widget($args, $instance) {
        echo $args['before_widget'];
        if (!empty($instance['title'])) {
            echo $args['before_title'] . apply_filters('widget_title', $instance['title']) . $args['after_title'];
        }
        echo do_shortcode('[affiliate_coupons count=' . intval($instance['count']) . ']');
        echo $args['after_widget'];
    }

    public function form($instance) {
        $title = !empty($instance['title']) ? $instance['title'] : __('Coupons & Deals', 'acdm');
        $count = !empty($instance['count']) ? intval($instance['count']) : 3;
        ?>
        <p>
          <label for="<?php echo $this->get_field_id('title'); ?>"><?php _e('Title:'); ?></label>
          <input class="widefat" id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name('title'); ?>" type="text" value="<?php echo esc_attr($title); ?>">
        </p>
        <p>
          <label for="<?php echo $this->get_field_id('count'); ?>"><?php _e('Number of coupons to show:'); ?></label>
          <input id="<?php echo $this->get_field_id('count'); ?>" name="<?php echo $this->get_field_name('count'); ?>" type="number" value="<?php echo esc_attr($count); ?>" min="1" max="20">
        </p>
        <?php
    }

    public function update($new_instance, $old_instance) {
        $instance = array();
        $instance['title'] = (!empty($new_instance['title'])) ? sanitize_text_field($new_instance['title']) : '';
        $instance['count'] = (!empty($new_instance['count']) && is_numeric($new_instance['count'])) ? intval($new_instance['count']) : 3;
        return $instance;
    }
}

new Affiliate_Coupons_Deals();