/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Coupon___Deal_Booster.php
*/
<?php
/**
 * Plugin Name: Affiliate Coupon & Deal Booster
 * Description: Manage exclusive affiliate coupons and deals with easy shortcodes and admin dashboard.
 * Version: 1.0
 * Author: Generated by AI
 * License: GPL2
 */

if (!defined('ABSPATH')) exit;

class AffiliateCouponBooster {
    private $coupons_option = 'acb_coupons';

    public function __construct() {
        add_action('admin_menu', array($this, 'acb_add_admin_menu'));
        add_action('admin_init', array($this, 'acb_settings_init'));
        add_shortcode('affiliate_coupons', array($this, 'acb_render_coupons_shortcode'));
        add_action('wp_enqueue_scripts', array($this, 'acb_enqueue_styles'));
    }

    public function acb_add_admin_menu() {
        add_menu_page('Affiliate Coupons', 'Affiliate Coupons', 'manage_options', 'affiliate_coupon_booster', array($this, 'acb_options_page'), 'dashicons-tickets-alt', 60);
    }

    public function acb_settings_init() {
        register_setting('acb_settings', $this->coupons_option, array($this, 'acb_sanitize_coupons'));

        add_settings_section('acb_section', __('Manage Your Affiliate Coupons', 'acb'), null, 'acb_settings');

        add_settings_field(
            'acb_coupons_field',
            __('Coupons Data (JSON Format)', 'acb'),
            array($this, 'acb_coupons_field_render'),
            'acb_settings',
            'acb_section'
        );
    }

    public function acb_coupons_field_render() {
        $options = get_option($this->coupons_option, '[]');
        echo '<textarea style="width:100%;height:300px;font-family: monospace;" name="'.esc_attr($this->coupons_option).'">'.esc_textarea(json_encode(json_decode($options), JSON_PRETTY_PRINT)).'</textarea>';
        echo '<p class="description">Enter coupons as JSON array. Each coupon requires title, code, url, description, and expiry (Y-m-d). Example: [{"title":"20% OFF","code":"SAVE20","url":"https://affiliate.example.com/product?code=SAVE20","description":"Save 20% on selected products","expiry":"2026-12-31"}]</p>';
    }

    public function acb_sanitize_coupons($input) {
        $decoded = json_decode($input, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            add_settings_error($this->coupons_option, 'invalid_json', 'Invalid JSON format. Please correct and save again.');
            return get_option($this->coupons_option);
        }
        // Validate structure
        foreach ($decoded as $coupon) {
            if (!isset($coupon['title'], $coupon['code'], $coupon['url'], $coupon['description'], $coupon['expiry'])) {
                add_settings_error($this->coupons_option, 'missing_fields', 'Each coupon must have title, code, url, description, and expiry.');
                return get_option($this->coupons_option);
            }
        }
        return $input;
    }

    public function acb_options_page() {
        ?>
        <div class="wrap">
            <h1>Affiliate Coupon & Deal Booster</h1>
            <form action="options.php" method="post">
                <?php
                settings_fields('acb_settings');
                do_settings_sections('acb_settings');
                submit_button('Save Coupons');
                ?>
            </form>
            <h2>Usage</h2>
            <p>Use shortcode <code>[affiliate_coupons]</code> in your posts or pages to display active affiliate coupons.</p>
        </div>
        <?php
    }

    public function acb_render_coupons_shortcode() {
        $coupons_json = get_option($this->coupons_option, '[]');
        $coupons = json_decode($coupons_json, true);
        if (!$coupons || !is_array($coupons)) return '<p>No coupons available.</p>';

        $output = '<div class="acb-coupons">';
        $today = date('Y-m-d');
        foreach ($coupons as $coupon) {
            if ($coupon['expiry'] >= $today) {
                $output .= '<div class="acb-coupon">';
                $output .= '<h3>'.esc_html($coupon['title']).'</h3>';
                $output .= '<p>'.esc_html($coupon['description']).'</p>';
                $output .= '<p><strong>Code: </strong><code>'.esc_html($coupon['code']).'</code></p>';
                $output .= '<p><a href="'.esc_url($coupon['url']).'" target="_blank" rel="nofollow noopener noreferrer" class="acb-btn">Use Coupon</a></p>';
                $output .= '<p class="acb-expiry">Expires: '.esc_html($coupon['expiry']).'</p>';
                $output .= '</div>';
            }
        }
        $output .= '</div>';

        return $output;
    }

    public function acb_enqueue_styles() {
        wp_register_style('acb_style', plugins_url('style.css', __FILE__));
        wp_enqueue_style('acb_style');
    }
}

new AffiliateCouponBooster();

// Inline CSS for simplicity
add_action('wp_head', function() {
    echo '<style>
    .acb-coupons { display: flex; flex-wrap: wrap; gap: 20px; margin: 20px 0; }
    .acb-coupon { background: #f9f9f9; border: 1px solid #ddd; border-radius: 6px; padding: 16px; flex: 1 1 300px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
    .acb-coupon h3 { margin-top: 0; color: #2a2a2a; }
    .acb-coupon code { background: #eee; padding: 4px 6px; border-radius: 4px; font-weight: bold; }
    .acb-btn { display: inline-block; margin-top: 10px; padding: 10px 20px; background: #0073aa; color: #fff; text-decoration: none; border-radius: 4px; font-weight: 600; }
    .acb-btn:hover { background: #005177; }
    .acb-expiry { color: #999; font-size: 0.9em; margin-top: 8px; }
    </style>';
});