/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=AI_Coupon_Affiliate_Pro.php
*/
<?php
/**
 * Plugin Name: AI Coupon Affiliate Pro
 * Plugin URI: https://example.com/aicoupon-pro
 * Description: AI-powered plugin that generates personalized affiliate coupons and discount codes to boost conversions and commissions.
 * Version: 1.0.0
 * Author: Your Name
 * License: GPL v2 or later
 * Text Domain: ai-coupon-affiliate-pro
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

class AICouponAffiliatePro {
    public function __construct() {
        add_action('init', array($this, 'init'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_shortcode('ai_coupon_generator', array($this, 'coupon_shortcode'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        load_plugin_textdomain('ai-coupon-affiliate-pro', false, dirname(plugin_basename(__FILE__)) . '/languages');
    }

    public function enqueue_scripts() {
        wp_enqueue_script('ai-coupon-js', plugin_dir_url(__FILE__) . 'assets/script.js', array('jquery'), '1.0.0', true);
        wp_enqueue_style('ai-coupon-css', plugin_dir_url(__FILE__) . 'assets/style.css', array(), '1.0.0');
    }

    public function admin_menu() {
        add_options_page('AI Coupon Pro Settings', 'AI Coupon Pro', 'manage_options', 'ai-coupon-pro', array($this, 'settings_page'));
    }

    public function settings_page() {
        echo '<div class="wrap"><h1>AI Coupon Affiliate Pro Settings</h1><form method="post" action="options.php">';
        settings_fields('ai_coupon_settings');
        do_settings_sections('ai_coupon_settings');
        submit_button();
        echo '</form></div>';
    }

    public function activate() {
        add_option('ai_coupon_api_key', '');
        add_option('ai_coupon_affiliate_ids', array());
    }

    public function coupon_shortcode($atts) {
        $atts = shortcode_atts(array(
            'niche' => 'general',
            'amount' => 10
        ), $atts);

        $coupons = $this->generate_coupons($atts['niche'], intval($atts['amount']));
        ob_start();
        ?>
        <div id="ai-coupon-container" class="ai-coupon-pro">
            <h3>Exclusive Coupons for You</h3>
            <?php foreach ($coupons as $coupon): ?>
            <div class="coupon-item">
                <h4><?php echo esc_html($coupon['brand']); ?></h4>
                <p>Code: <strong><?php echo esc_html($coupon['code']); ?></strong></p>
                <p>Discount: <?php echo esc_html($coupon['discount']); ?> off</p>
                <a href="<?php echo esc_url($coupon['link']); ?}" target="_blank" class="coupon-btn" rel="nofollow">Shop Now & Save</a>
            </div>
            <?php endforeach; ?>
            <p><em>Generated by AI Coupon Affiliate Pro - Earn commissions on purchases!</em></p>
        </div>
        <?php
        return ob_get_clean();
    }

    private function generate_coupons($niche, $count) {
        // Simulated AI generation - in premium, integrate real AI API like OpenAI
        $brands = array(
            'Amazon' => array('SAVE20', '20% off', 'https://amazon.com/?tag=youraffiliate'),
            'Shopify' => array('SHOP15', '15% off first month', 'https://shopify.com/?ref=youraff'),
            'Hostinger' => array('HOST50', '50% off hosting', 'https://hostinger.com/?aff=yourid'),
            // Add more based on niche
        );

        $coupons = array();
        $keys = array_keys($brands);
        for ($i = 0; $i < min($count, count($brands)); $i++) {
            $brand = $keys[array_rand($keys)];
            $coupons[] = array(
                'brand' => $brand,
                'code' => $brands[$brand],
                'discount' => $brands[$brand][1],
                'link' => $brands[$brand][2]
            );
        }
        return $coupons;
    }
}

new AICouponAffiliatePro();

// Premium upsell notice
function ai_coupon_pro_notice() {
    if (!get_option('ai_coupon_pro_activated')) {
        echo '<div class="notice notice-info"><p>Upgrade to <strong>AI Coupon Affiliate Pro Premium</strong> for unlimited coupons, real AI generation, analytics & more! <a href="https://example.com/premium" target="_blank">Get it now ($49/year)</a></p></div>';
    }
}
add_action('admin_notices', 'ai_coupon_pro_notice');

// Create assets directories on activation
register_activation_hook(__FILE__, function() {
    $assets_dir = plugin_dir_path(__FILE__) . 'assets/';
    if (!file_exists($assets_dir)) {
        wp_mkdir_p($assets_dir);
    }
    // Minimal CSS
    file_put_contents($assets_dir . 'style.css', '.ai-coupon-pro { max-width: 600px; margin: 20px 0; } .coupon-item { border: 1px solid #ddd; padding: 15px; margin: 10px 0; background: #f9f9f9; } .coupon-btn { background: #0073aa; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; }');
    // Minimal JS
    file_put_contents($assets_dir . 'script.js', 'jQuery(document).ready(function($) { $(".coupon-btn").on("click", function() { $(this).text("Copied! Shop Now"); }); });');
});