/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=AI_Coupon_Affiliate_Pro.php
*/
<?php
/**
 * Plugin Name: AI Coupon Affiliate Pro
 * Plugin URI: https://example.com/aicoupon-pro
 * Description: Generate and manage personalized AI-powered coupons with affiliate tracking for bloggers and eCommerce sites.
 * Version: 1.0.0
 * Author: Your Name
 * License: GPL v2 or later
 * Text Domain: ai-coupon-affiliate-pro
 */

if (!defined('ABSPATH')) {
    exit;
}

class AICouponAffiliatePro {
    public function __construct() {
        add_action('init', array($this, 'init'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_shortcode('ai_coupon_generator', array($this, 'coupon_shortcode'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        load_plugin_textdomain('ai-coupon-affiliate-pro', false, dirname(plugin_basename(__FILE__)) . '/languages');
    }

    public function enqueue_scripts() {
        wp_enqueue_script('ai-coupon-js', plugin_dir_url(__FILE__) . 'assets/script.js', array('jquery'), '1.0.0', true);
        wp_enqueue_style('ai-coupon-css', plugin_dir_url(__FILE__) . 'assets/style.css', array(), '1.0.0');
    }

    public function admin_menu() {
        add_options_page('AI Coupon Pro', 'AI Coupon Pro', 'manage_options', 'ai-coupon-pro', array($this, 'admin_page'));
    }

    public function admin_page() {
        if (isset($_POST['save'])) {
            update_option('ai_coupon_api_key', sanitize_text_field($_POST['api_key']));
            update_option('ai_coupon_affiliate_id', sanitize_text_field($_POST['affiliate_id']));
            echo '<div class="notice notice-success"><p>Settings saved!</p></div>';
        }
        $api_key = get_option('ai_coupon_api_key', '');
        $affiliate_id = get_option('ai_coupon_affiliate_id', '');
        ?>
        <div class="wrap">
            <h1>AI Coupon Affiliate Pro Settings</h1>
            <form method="post">
                <table class="form-table">
                    <tr>
                        <th>OpenAI API Key</th>
                        <td><input type="text" name="api_key" value="<?php echo esc_attr($api_key); ?>" class="regular-text" /></td>
                    </tr>
                    <tr>
                        <th>Affiliate ID</th>
                        <td><input type="text" name="affiliate_id" value="<?php echo esc_attr($affiliate_id); ?>" class="regular-text" /></td>
                    </tr>
                </table>
                <p class="submit"><input type="submit" name="save" class="button-primary" value="Save Settings" /></p>
            </form>
            <h2>Usage</h2>
            <p>Use shortcode: <code>[ai_coupon_generator niche="fashion"]</code></p>
            <p><strong>Pro Features:</strong> Unlimited generations, custom domains, analytics. <a href="https://example.com/pro">Upgrade Now</a></p>
        </div>
        <?php
    }

    public function coupon_shortcode($atts) {
        $atts = shortcode_atts(array(
            'niche' => 'general',
            'discount' => '20',
        ), $atts);

        $api_key = get_option('ai_coupon_api_key');
        if (!$api_key) {
            return '<p><strong>Pro:</strong> Enter OpenAI API key in settings for AI coupons!</p>';
        }

        $affiliate_id = get_option('ai_coupon_affiliate_id');
        $link = $affiliate_id ? 'https://affiliate.com/?id=' . $affiliate_id : 'https://example.com/shop';

        // Mock AI generation (replace with real OpenAI API call in pro)
        $coupon_code = strtoupper(substr(md5($atts['niche'] . time()), 0, 8));
        $description = 'AI-Generated: Save ' . $atts['discount'] . '% on ' . ucwords($atts['niche']) . ' items! ' . $this->mock_ai_prompt($atts['niche']);

        ob_start();
        ?>
        <div class="ai-coupon-container">
            <div class="coupon-code"><?php echo esc_html($coupon_code); ?></div>
            <p class="coupon-desc"><?php echo esc_html($description); ?></p>
            <a href="<?php echo esc_url($link); ?>" class="coupon-btn" target="_blank">Redeem Now & Track Affiliate</a>
            <small>Generated by AI Coupon Pro</small>
        </div>
        <?php
        return ob_get_clean();
    }

    private function mock_ai_prompt($niche) {
        $prompts = array(
            'fashion' => 'Perfect for trendy outfits this season. Limited time!',
            'tech' => 'Upgrade your gadgets with exclusive savings.',
            'general' => 'Great deals on top products.'
        );
        return isset($prompts[$niche]) ? $prompts[$niche] : $prompts['general'];
    }

    public function activate() {
        add_option('ai_coupon_version', '1.0.0');
    }
}

new AICouponAffiliatePro();

// Inline assets for single-file

function ai_coupon_assets() {
    ?>
    <style>
    .ai-coupon-container { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; text-align: center; max-width: 400px; margin: 20px auto; box-shadow: 0 10px 30px rgba(0,0,0,0.3); }
    .coupon-code { font-size: 2.5em; font-weight: bold; letter-spacing: 5px; margin-bottom: 10px; }
    .coupon-desc { font-size: 1.1em; margin-bottom: 15px; }
    .coupon-btn { background: #ff6b6b; color: white; padding: 12px 30px; text-decoration: none; border-radius: 25px; font-weight: bold; display: inline-block; transition: all 0.3s; }
    .coupon-btn:hover { background: #ff5252; transform: translateY(-2px); }
    </style>
    <script>
    jQuery(document).ready(function($) {
        $('.ai-coupon-container').on('click', '.coupon-btn', function() {
            gtag('event', 'coupon_click', {'niche': '<?php echo esc_js($atts['niche']); ?>'});
        });
    });
    </script>
    <?php
}

add_action('wp_head', 'ai_coupon_assets');

// Pro upsell notice
function ai_coupon_admin_notice() {
    if (!get_option('ai_coupon_api_key')) {
        echo '<div class="notice notice-info"><p>🚀 <strong>AI Coupon Pro:</strong> Unlock unlimited AI coupons & analytics. <a href="' . admin_url('options-general.php?page=ai-coupon-pro') . '">Upgrade</a></p></div>';
    }
}

add_action('admin_notices', 'ai_coupon_admin_notice');