/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=AI_Coupon_Affiliate_Pro.php
*/
<?php
/**
 * Plugin Name: AI Coupon Affiliate Pro
 * Plugin URI: https://example.com/aicoupon-pro
 * Description: AI-powered coupon and affiliate deal generator for WordPress. Free version generates basic coupons; Pro unlocks advanced features.
 * Version: 1.0.0
 * Author: Your Name
 * Author URI: https://example.com
 * License: GPL v2 or later
 * Text Domain: ai-coupon-pro
 */

if (!defined('ABSPATH')) {
    exit;
}

class AICouponAffiliatePro {
    private static $instance = null;

    public static function get_instance() {
        if (null == self::$instance) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        add_action('init', array($this, 'init'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_shortcode('ai_coupon_generator', array($this, 'coupon_shortcode'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        load_plugin_textdomain('ai-coupon-pro', false, dirname(plugin_basename(__FILE__)) . '/languages');
        if (is_admin()) {
            add_action('admin_init', array($this, 'admin_init'));
        }
    }

    public function enqueue_scripts() {
        wp_enqueue_style('ai-coupon-style', plugin_dir_url(__FILE__) . 'style.css', array(), '1.0.0');
        wp_enqueue_script('ai-coupon-script', plugin_dir_url(__FILE__) . 'script.js', array('jquery'), '1.0.0', true);
    }

    public function admin_menu() {
        add_options_page('AI Coupon Pro Settings', 'AI Coupon Pro', 'manage_options', 'ai-coupon-pro', array($this, 'settings_page'));
    }

    public function admin_init() {
        register_setting('ai_coupon_pro_settings', 'ai_coupon_pro_options');
        add_settings_section('ai_coupon_main', 'Main Settings', null, 'ai-coupon-pro');
        add_settings_field('affiliate_links', 'Affiliate Links (JSON)', array($this, 'affiliate_links_field'), 'ai-coupon-pro', 'ai_coupon_main');
        add_settings_field('pro_upgrade', 'Upgrade to Pro', array($this, 'pro_upgrade_field'), 'ai-coupon-pro', 'ai_coupon_main');
    }

    public function settings_page() {
        ?>
        <div class="wrap">
            <h1>AI Coupon Affiliate Pro</h1>
            <form method="post" action="options.php">
                <?php
                settings_fields('ai_coupon_pro_settings');
                do_settings_sections('ai-coupon-pro');
                submit_button();
                ?>
            </form>
            <div class="pro-notice notice notice-info"><p><strong>Pro Features:</strong> Unlimited coupons, AI analytics, custom designs. <a href="https://example.com/pro" target="_blank">Upgrade Now ($49/year)</a></p></div>
        </div>
        <?php
    }

    public function affiliate_links_field() {
        $options = get_option('ai_coupon_pro_options', array('affiliates' => '{"amazon":"https://amazon.com/?tag=yourtag","example":"https://example.com/aff"}'));
        echo '<textarea name="ai_coupon_pro_options[affiliates]" rows="5" cols="50">' . esc_textarea($options['affiliates']) . '</textarea><p>JSON format: {"brand":"affiliate_url"}</p>';
    }

    public function pro_upgrade_field() {
        echo '<p><a href="https://example.com/pro" class="button button-primary" target="_blank">Get Pro Version</a> for advanced AI features and unlimited usage.</p>';
    }

    public function coupon_shortcode($atts) {
        $atts = shortcode_atts(array('brand' => ''), $atts);
        $options = get_option('ai_coupon_pro_options', array());
        $affiliates = json_decode($options['affiliates'] ?? '{}', true);
        $brand = $atts['brand'] ?: array_key_first($affiliates);
        $url = $affiliates[$brand] ?? '#';
        $coupon_code = 'SAVE' . wp_rand(10, 99) . '%'; // Simple AI-like generation
        $discount = wp_rand(10, 50) . '% OFF';

        // Free version limit
        static $usage = 0;
        if ($usage >= 5 && !defined('AIC_PRO')) {
            return '<p>Upgrade to Pro for unlimited coupons!</p>';
        }
        $usage++;

        ob_start();
        ?>
        <div class="ai-coupon-box">
            <h3>Exclusive Deal: <?php echo esc_html($brand); ?></h3>
            <p><strong><?php echo esc_html($discount); ?></strong> with code: <code><?php echo esc_html($coupon_code); ?></code></p>
            <a href="<?php echo esc_url($url); ?>" class="coupon-btn" target="_blank">Shop Now & Save</a>
            <small>Generated by AI Coupon Pro</small>
        </div>
        <style>
        .ai-coupon-box { border: 2px solid #007cba; padding: 20px; border-radius: 10px; background: #f9f9f9; text-align: center; }
        .coupon-btn { background: #007cba; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block; }
        .coupon-btn:hover { background: #005a87; }
        </style>
        <?php
        return ob_get_clean();
    }

    public function activate() {
        add_option('ai_coupon_pro_options', array('affiliates' => '{"amazon":"https://amazon.com/?tag=yourtag"}'));
    }
}

AICouponAffiliatePro::get_instance();

// Pro check (simulate)
if (get_option('ai_coupon_pro_license') === 'valid') {
    define('AIC_PRO', true);
}

// Inline CSS/JS for self-contained
add_action('wp_head', function() {
    echo '<style>.pro-notice { margin: 20px 0; padding: 15px; }</style>';
});

// Usage: [ai_coupon_generator brand="amazon"]

?>