/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=AffiliateDeal_Booster.php
*/
<?php
/**
 * Plugin Name: AffiliateDeal Booster
 * Description: Dynamically generate exclusive affiliate coupon deals personalized per visitor to improve affiliate conversions.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) exit; // Exit if accessed directly

class AffiliateDealBooster {

    private $affiliates = array(
        // Example: affiliate_id => array(coupon_code, discount_desc, affiliate_url)
        'amazon' => array('AMZ2025', '10% off Amazon products', 'https://www.amazon.com/dp/productid?tag=affiliateid'),
        'ebay' => array('EBY2025', '15% off eBay deals', 'https://www.ebay.com/itm/itemid?campid=affiliateid'),
        'bestbuy' => array('BBY2025', '20$ off BestBuy purchase', 'https://www.bestbuy.com/site/productid?ref=affiliateid')
    );

    public function __construct() {
        add_shortcode('affiliate_deal_booster', array($this, 'render_deal_shortcode'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('wp_footer', array($this, 'inject_dynamic_deal_script'));
    }

    public function enqueue_scripts() {
        wp_enqueue_style('affiliate-deal-booster-style', plugin_dir_url(__FILE__) . 'style.css');
    }

    public function render_deal_shortcode($atts) {
        $atts = shortcode_atts(array('default_affiliate' => 'amazon'), $atts, 'affiliate_deal_booster');
        ob_start();
        ?>
        <div id="affiliate-deal-booster-wrapper" style="border:1px solid #ccc; padding:15px; max-width:300px; font-family:Arial,sans-serif;">
            <h3>Exclusive Deal Just for You</h3>
            <p id="adb-discount-desc">Loading your best discount...</p>
            <a href="#" id="adb-affiliate-link" target="_blank" rel="nofollow noopener noreferrer" style="display:inline-block; margin-top:10px; background:#0073aa; color:#fff; padding:8px 12px; text-decoration:none; border-radius:3px;">Grab this Deal</a>
        </div>
        <script>
        window.adb_affiliate_data = <?php echo json_encode($this->affiliates); ?>;
        </script>
        <?php
        return ob_get_clean();
    }

    public function inject_dynamic_deal_script() {
        ?>
        <script>
        (function(){
            function selectBestDeal() {
                // Simple heuristic: select a random affiliate deal (simulate personalization)
                var affiliates = window.adb_affiliate_data;
                var keys = Object.keys(affiliates);
                if (keys.length === 0) return null;
                var index = Math.floor(Math.random()*keys.length);
                return affiliates[keys[index]];
            }
            document.addEventListener('DOMContentLoaded', function(){
                var deal = selectBestDeal();
                if(deal){
                    var descElem = document.getElementById('adb-discount-desc');
                    var linkElem = document.getElementById('adb-affiliate-link');
                    if(descElem) descElem.textContent = deal[1];
                    if(linkElem){
                      linkElem.href = deal[2];
                      linkElem.textContent = 'Grab this Deal';
                    }
                }
            });
        })();
        </script>
        <?php
    }
}

new AffiliateDealBooster();
