/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=AI_Content_Profit_Shield.php
*/
<?php
/**
 * Plugin Name: AI Content Profit Shield
 * Plugin URI: https://example.com/aicps
 * Description: Detects AI-generated content and monetizes it automatically with affiliates, ads, and premium features.
 * Version: 1.0.0
 * Author: Profit Plugins
 * License: GPL v2 or later
 */

if (!defined('ABSPATH')) exit;

class AIContentProfitShield {
    public function __construct() {
        add_action('init', array($this, 'init'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_filter('the_content', array($this, 'monetize_content'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_action('wp_ajax_aicps_scan', array($this, 'ajax_scan'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        if (get_option('aicps_pro') !== 'yes') {
            add_action('wp_footer', array($this, 'footer_ads'));
        }
    }

    public function enqueue_scripts() {
        wp_enqueue_script('aicps-js', plugin_dir_url(__FILE__) . 'aicps.js', array('jquery'), '1.0.0', true);
        wp_localize_script('aicps-js', 'aicps_ajax', array('ajaxurl' => admin_url('admin-ajax.php')));
    }

    public function monetize_content($content) {
        $ai_score = $this->detect_ai_content($content);
        if ($ai_score > 0.7) {
            $content .= $this->insert_affiliate_links($content);
            if (get_option('aicps_pro') !== 'yes') {
                $content .= '<div class="aicps-upgrade"><p><strong>AI Detected (Score: ' . round($ai_score*100) . '%)</strong> - <a href="https://example.com/pro" target="_blank">Upgrade to Pro</a> for humanizer & more!</p></div>';
            }
        }
        return $content;
    }

    private function detect_ai_content($text) {
        $keywords = array('Certainly', 'As an AI', 'Generated by', 'The following', 'Delve into');
        $score = 0;
        foreach ($keywords as $kw) {
            if (stripos($text, $kw) !== false) $score += 0.2;
        }
        $sentences = preg_split('/[.!?]+/', $text);
        $avg_len = array_sum(array_map('strlen', $sentences)) / count($sentences);
        if ($avg_len > 150) $score += 0.3;
        return min(1, $score);
    }

    private function insert_affiliate_links($content) {
        $aff_links = array(
            'content' => 'Check out <a href="https://example.com/aff1" target="_blank" rel="nofollow">Jasper AI</a> for better content!',
            'seo' => '<a href="https://example.com/aff2" target="_blank" rel="nofollow">Yoast SEO Plugin</a>',
            'monetize' => '<a href="https://example.com/aff3" target="_blank" rel="nofollow">AffiliateWP</a>'
        );
        $insert = $aff_links[array_rand($aff_links)];
        return '<div class="aicps-monetize">' . $insert . '</div>';
    }

    public function footer_ads() {
        echo '<div class="aicps-ad" style="text-align:center;padding:20px;background:#f0f0f0;margin:20px 0;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-XXXX" data-ad-slot="XXXX" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div>';
    }

    public function admin_menu() {
        add_options_page('AI Content Profit Shield', 'AI Profit Shield', 'manage_options', 'aicps', array($this, 'admin_page'));
    }

    public function admin_page() {
        if (isset($_POST['aicps_scan'])) {
            $this->ajax_scan();
        }
        echo '<div class="wrap"><h1>AI Content Profit Shield</h1><form method="post"><input type="submit" name="aicps_scan" value="Scan Site for AI Content" class="button-primary"><p>Pro: ' . (get_option('aicps_pro') === 'yes' ? 'Activated' : '<a href="https://example.com/pro">Buy Now $49</a>') . '</p></form></div>';
    }

    public function ajax_scan() {
        $posts = get_posts(array('numberposts' => 5));
        $ai_posts = array();
        foreach ($posts as $post) {
            $score = $this->detect_ai_content($post->post_content);
            if ($score > 0.7) $ai_posts[] = $post->post_title . ' (Score: ' . round($score*100) . '%)';
        }
        wp_send_json(array('ai_posts' => $ai_posts));
    }

    public function activate() {
        add_option('aicps_pro', 'no');
    }
}

new AIContentProfitShield();

// Dummy JS file content (in real plugin, separate file)
/*
jQuery(document).ready(function($) {
    $('.aicps-upgrade').on('click', function() {
        alert('Upgrade to Pro for full features!');
    });
});
*/