/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=AI_Coupon_Generator_Pro.php
*/
<?php
/**
 * Plugin Name: AI Coupon Generator Pro
 * Plugin URI: https://example.com/aicouponpro
 * Description: AI-powered coupon generator for affiliate marketing and monetization.
 * Version: 1.0.0
 * Author: Your Name
 * License: GPL v2 or later
 * Text Domain: ai-coupon-pro
 */

if (!defined('ABSPATH')) {
    exit;
}

class AICouponGeneratorPro {
    public function __construct() {
        add_action('init', array($this, 'init'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_shortcode('ai_coupon_generator', array($this, 'coupon_shortcode'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        load_plugin_textdomain('ai-coupon-pro', false, dirname(plugin_basename(__FILE__)) . '/languages');
    }

    public function enqueue_scripts() {
        wp_enqueue_script('ai-coupon-pro', plugin_dir_url(__FILE__) . 'assets/script.js', array('jquery'), '1.0.0', true);
        wp_enqueue_style('ai-coupon-pro', plugin_dir_url(__FILE__) . 'assets/style.css', array(), '1.0.0');
    }

    public function admin_menu() {
        add_options_page('AI Coupon Pro Settings', 'AI Coupon Pro', 'manage_options', 'ai-coupon-pro', array($this, 'settings_page'));
    }

    public function settings_page() {
        if (isset($_POST['submit'])) {
            update_option('ai_coupon_pro_api_key', sanitize_text_field($_POST['api_key']));
            update_option('ai_coupon_pro_affiliate_id', sanitize_text_field($_POST['affiliate_id']));
            echo '<div class="notice notice-success"><p>Settings saved!</p></div>';
        }
        $api_key = get_option('ai_coupon_pro_api_key', '');
        $affiliate_id = get_option('ai_coupon_pro_affiliate_id', '');
        ?>
        <div class="wrap">
            <h1>AI Coupon Generator Pro Settings</h1>
            <form method="post">
                <table class="form-table">
                    <tr>
                        <th>OpenAI API Key (Premium)</th>
                        <td><input type="text" name="api_key" value="<?php echo esc_attr($api_key); ?>" class="regular-text" placeholder="sk-..."></td>
                    </tr>
                    <tr>
                        <th>Your Affiliate ID</th>
                        <td><input type="text" name="affiliate_id" value="<?php echo esc_attr($affiliate_id); ?>" class="regular-text"></td>
                    </tr>
                </table>
                <?php submit_button(); ?>
            </form>
            <p><strong>Upgrade to Pro</strong> for AI generation, unlimited coupons, and analytics. <a href="https://example.com/pricing" target="_blank">Get Pro</a></p>
        </div>
        <?php
    }

    public function coupon_shortcode($atts) {
        $atts = shortcode_atts(array(
            'niche' => 'general',
            'discount' => '20',
            'expires' => '+30 days'
        ), $atts);

        $coupon_code = $this->generate_coupon_code($atts['niche']);
        $affiliate_id = get_option('ai_coupon_pro_affiliate_id', '');
        $aff_link = $affiliate_id ? "?aff={$affiliate_id}" : '';
        $expires = date('Y-m-d', strtotime($atts['expires']));

        $coupon_html = "
        <div class=\"ai-coupon-box\">
            <h3>Exclusive Deal: Save {$atts['discount']}%!</h3>
            <div class=\"coupon-code\">{$coupon_code}</div>
            <p>Expires: {$expires}</p>
            <a href=\"https://partner-site.com{$aff_link}\" class=\"coupon-btn\" target=\"_blank\">Shop Now & Apply Code</a>
            <small>Generated by AI Coupon Pro</small>
        </div>
        ";

        return $coupon_html;
    }

    private function generate_coupon_code($niche) {
        $prefixes = array(
            'general' => 'SAVE',
            'tech' => 'TECH',
            'fashion' => 'STYLE',
            'food' => 'EAT'
        );
        $prefix = isset($prefixes[$niche]) ? $prefixes[$niche] : 'DEAL';
        return $prefix . wp_generate_password(6, false, false);
    }

    public function activate() {
        flush_rewrite_rules();
    }
}

new AICouponGeneratorPro();

// Premium teaser
add_action('admin_notices', function() {
    if (!get_option('ai_coupon_pro_dismissed')) {
        echo '<div class="notice notice-info"><p>Unlock <strong>AI Coupon Generator Pro</strong> features: Real AI coupon creation, analytics & more! <a href="https://example.com/pricing" target="_blank">Upgrade Now</a> | <a href="?ai_coupon_dismiss=1">Dismiss</a></p></div>';
    }
});

if (isset($_GET['ai_coupon_dismiss'])) {
    update_option('ai_coupon_pro_dismissed', 1);
    wp_redirect(admin_url());
    exit;
}

// CSS
add_action('wp_head', function() {
    echo '<style>
    .ai-coupon-box { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; text-align: center; max-width: 300px; margin: 20px auto; box-shadow: 0 10px 30px rgba(0,0,0,0.3); }
    .coupon-code { font-size: 2em; font-weight: bold; background: rgba(255,255,255,0.2); padding: 10px; border-radius: 5px; margin: 10px 0; letter-spacing: 3px; }
    .coupon-btn { display: inline-block; background: #ff6b6b; color: white; padding: 12px 24px; text-decoration: none; border-radius: 25px; font-weight: bold; margin-top: 10px; transition: transform 0.3s; }
    .coupon-btn:hover { transform: scale(1.05); }
    </style>';
});

// JS
add_action('wp_footer', function() {
    echo '<script>
    jQuery(document).ready(function($) {
        $(".coupon-btn").on("click", function() {
            $(this).text("Copied! Apply at checkout").css("background", "#4ecdc4");
            setTimeout(() => location.href = this.href, 1000);
        });
    });
    </script>';
});