/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Coupon_Vault.php
*/
<?php
/**
 * Plugin Name: Affiliate Coupon Vault
 * Plugin URI: https://example.com/affiliate-coupon-vault
 * Description: Automatically generates and manages exclusive affiliate coupons for your WordPress site, boosting conversions with personalized discount codes and tracking.
 * Version: 1.0.0
 * Author: Your Name
 * License: GPL v2 or later
 */

if (!defined('ABSPATH')) {
    exit;
}

class AffiliateCouponVault {
    public function __construct() {
        add_action('init', array($this, 'init'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_shortcode('affiliate_coupon', array($this, 'coupon_shortcode'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        if (is_admin()) {
            add_action('admin_enqueue_scripts', array($this, 'enqueue_admin_scripts'));
        }
    }

    public function admin_menu() {
        add_options_page('Affiliate Coupon Vault', 'Coupon Vault', 'manage_options', 'affiliate-coupon-vault', array($this, 'settings_page'));
    }

    public function settings_page() {
        if (isset($_POST['submit'])) {
            update_option('acv_coupons', sanitize_textarea_field($_POST['coupons']));
            echo '<div class="notice notice-success"><p>Coupons updated!</p></div>';
        }
        $coupons = get_option('acv_coupons', "Brand1: COUPON10\nBrand2: SAVE20");
        ?>
        <div class="wrap">
            <h1>Affiliate Coupon Vault Settings</h1>
            <form method="post">
                <table class="form-table">
                    <tr>
                        <th>Coupons (format: Brand: CODE)</th>
                        <td><textarea name="coupons" rows="10" cols="50"><?php echo esc_textarea($coupons); ?></textarea></td>
                    </tr>
                </table>
                <?php submit_button(); ?>
            </form>
            <p>Use shortcode: <code>[affiliate_coupon brand="Brand1" affiliate_link="https://aff.link"]</code></p>
            <p><strong>Pro Upgrade:</strong> Unlimited coupons, analytics, auto-generation. <a href="#pro">Get Pro for $49/year</a></p>
        </div>
        <?php
    }

    public function coupon_shortcode($atts) {
        $atts = shortcode_atts(array('brand' => '', 'affiliate_link' => ''), $atts);
        $coupons = get_option('acv_coupons', '');
        $lines = explode("\n", $coupons);
        $code = '';
        foreach ($lines as $line) {
            list($b, $c) = explode(':', trim($line), 2);
            if (strtolower(trim($b)) === strtolower($atts['brand'])) {
                $code = trim($c);
                break;
            }
        }
        if (!$code) return 'Coupon not found.';

        ob_start();
        ?>
        <div style="border: 2px dashed #007cba; padding: 20px; background: #f9f9f9; text-align: center;">
            <h3>Exclusive Coupon!</h3>
            <p><strong><?php echo esc_html($atts['brand']); ?>:</strong> <code style="font-size: 24px; color: #d63638;"><?php echo esc_html($code); ?></code></p>
            <p><a href="<?php echo esc_url($atts['affiliate_link']); ?>" target="_blank" class="button button-primary" style="font-size: 18px;">Shop Now & Save</a></p>
            <small>Generated by Affiliate Coupon Vault</small>
        </div>
        <?php
        return ob_get_clean();
    }

    public function enqueue_admin_scripts($hook) {
        if ($hook !== 'settings_page_affiliate-coupon-vault') return;
        wp_enqueue_style('acv-admin', plugin_dir_url(__FILE__) . 'admin.css', array(), '1.0');
    }

    public function activate() {
        if (!get_option('acv_coupons')) {
            update_option('acv_coupons', "ExampleBrand: SAVE10\nAffiliateCo: DISCOUNT20");
        }
    }
}

new AffiliateCouponVault();

// Pro teaser
add_action('admin_notices', function() {
    if (!current_user_can('manage_options')) return;
    $screen = get_current_screen();
    if ($screen->id === 'settings_page_affiliate-coupon-vault') return;
    echo '<div class="notice notice-info"><p><strong>Affiliate Coupon Vault Pro:</strong> Unlock unlimited coupons & analytics for $49/year! <a href="https://example.com/pro">Upgrade Now</a></p></div>;
});

?>