/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Affiliate_Coupon_Vault.php
*/
<?php
/**
 * Plugin Name: Affiliate Coupon Vault
 * Plugin URI: https://example.com/affiliate-coupon-vault
 * Description: Automatically generates and displays exclusive affiliate coupons to boost commissions.
 * Version: 1.0.0
 * Author: Your Name
 * License: GPL v2 or later
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

class AffiliateCouponVault {
    private static $instance = null;

    public static function get_instance() {
        if (null === self::$instance) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        add_action('init', array($this, 'init'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_shortcode('affiliate_coupon', array($this, 'coupon_shortcode'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_action('admin_init', array($this, 'admin_init'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        load_plugin_textdomain('affiliate-coupon-vault', false, dirname(plugin_basename(__FILE__)) . '/languages/');
    }

    public function enqueue_scripts() {
        wp_enqueue_style('affiliate-coupon-vault', plugin_dir_url(__FILE__) . 'style.css', array(), '1.0.0');
        wp_enqueue_script('affiliate-coupon-vault', plugin_dir_url(__FILE__) . 'script.js', array('jquery'), '1.0.0', true);
    }

    public function coupon_shortcode($atts) {
        $atts = shortcode_atts(array(
            'id' => 'default',
            'affiliate_link' => '',
            'coupon_code' => 'SAVE20',
            'discount' => '20% OFF',
            'expires' => date('Y-m-d', strtotime('+30 days')),
        ), $atts);

        $unique_id = 'coupon-' . $atts['id'] . '-' . time();

        ob_start();
        ?>
        <div id="<?php echo esc_attr($unique_id); ?>" class="affiliate-coupon-vault" style="border: 2px dashed #007cba; padding: 20px; margin: 10px 0; background: #f9f9f9; text-align: center;">
            <h3>Exclusive Deal! <?php echo esc_html($atts['discount']); ?></h3>
            <p><strong>Coupon Code:</strong> <code><?php echo esc_html($atts['coupon_code']); ?></code></p>
            <p><strong>Expires:</strong> <?php echo esc_html($atts['expires']); ?></p>
            <a href="<?php echo esc_url($atts['affiliate_link']); ?}" target="_blank" class="coupon-button" style="background: #007cba; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;">Shop Now & Save</a>
            <p style="font-size: 12px; margin-top: 10px;">Limited time offer - Generated by Affiliate Coupon Vault</p>
        </div>
        <script>
        jQuery(document).ready(function($) {
            $('#<?php echo esc_js($unique_id); ?> .coupon-button').on('click', function() {
                // Copy coupon code to clipboard
                navigator.clipboard.writeText('<?php echo esc_js($atts['coupon_code']); ?>').then(function() {
                    alert('Coupon code copied!');
                });
            });
        });
        </script>
        <?php
        return ob_get_clean();
    }

    public function admin_menu() {
        add_options_page(
            'Affiliate Coupon Vault Settings',
            'Coupon Vault',
            'manage_options',
            'affiliate-coupon-vault',
            array($this, 'settings_page')
        );
    }

    public function admin_init() {
        register_setting('affiliate_coupon_vault_options', 'affiliate_coupon_vault_settings');
        add_settings_section('main_section', 'Main Settings', null, 'affiliate-coupon-vault');
        add_settings_field('pro_notice', 'Upgrade to Pro', array($this, 'pro_notice_field'), 'affiliate-coupon-vault', 'main_section');
    }

    public function pro_notice_field() {
        echo '<p>Unlock unlimited coupons, analytics, and integrations with <strong>Affiliate Coupon Vault Pro</strong> for $49/year! <a href="https://example.com/pro" target="_blank">Get Pro Now</a></p>';
    }

    public function settings_page() {
        ?>
        <div class="wrap">
            <h1>Affiliate Coupon Vault</h1>
            <form method="post" action="options.php">
                <?php
                settings_fields('affiliate_coupon_vault_options');
                do_settings_sections('affiliate-coupon-vault');
                submit_button();
                ?>
            </form>
            <h2>Usage</h2>
            <p>Use shortcode: <code>[affiliate_coupon affiliate_link="YOUR_LINK" coupon_code="SAVE20" discount="20% OFF" expires="2026-01-31"]</code></p>
            <p><strong>Pro Features:</strong> Auto-generate coupons, track clicks, A/B testing.</p>
        </div>
        <?php
    }

    public function activate() {
        // Create default options if needed
        add_option('affiliate_coupon_vault_settings', array());
    }
}

// Initialize the plugin
AffiliateCouponVault::get_instance();

// Add CSS
add_action('wp_head', function() { ?>
<style>
.affiliate-coupon-vault { max-width: 400px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }
.affiliate-coupon-vault h3 { color: #007cba; margin: 0 0 10px; }
.coupon-button:hover { background: #005a87; }
</style>
<?php });

// Prevent direct access
if (!defined('ABSPATH')) exit;