/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=AffiliateDealTracker.php
*/
<?php
/**
 * Plugin Name: AffiliateDealTracker
 * Description: Aggregate and display affiliate coupons and deals with tracking and scheduling.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) exit; // Exit if accessed directly

class AffiliateDealTracker {
    private $option_name = 'adt_deals_store';

    public function __construct() {
        add_action('admin_menu', array($this, 'add_admin_menu'));
        add_action('admin_init', array($this, 'settings_init'));
        add_shortcode('affiliate_deals', array($this, 'shortcode_display_deals'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_styles'));
    }

    public function enqueue_styles() {
        wp_enqueue_style('adt_styles', plugin_dir_url(__FILE__) . 'adt_styles.css');
    }

    public function add_admin_menu() {
        add_menu_page('Affiliate Deals', 'Affiliate Deals', 'manage_options', 'affiliate_deal_tracker', array($this, 'admin_page'), 'dashicons-tickets', 61);
    }

    public function settings_init() {
        register_setting('adt_settings_group', $this->option_name);

        add_settings_section(
            'adt_settings_section',
            __('Manage Your Deals', 'affiliate-deal-tracker'),
            null,
            'affiliate_deal_tracker'
        );

        add_settings_field(
            'adt_deals_field',
            __('Deals JSON', 'affiliate-deal-tracker'),
            array($this, 'deals_field_render'),
            'affiliate_deal_tracker',
            'adt_settings_section'
        );
    }

    public function deals_field_render() {
        $options = get_option($this->option_name, '{}');
        echo '<textarea cols="80" rows="10" name="'. esc_attr($this->option_name) .'">' . esc_textarea($options) . '</textarea>';
        echo '<p class="description">Enter your deals as a JSON array. Each deal should have title, description, affiliate_url, expiration_date (Y-m-d), and optionally coupon_code.</p>';
        echo '<p>Example:<br>{ "deals": [ { "title": "20% Off Product", "description": "Save 20% with this exclusive offer", "affiliate_url": "https://example.com?ref=123", "expiration_date": "2025-12-31", "coupon_code": "SAVE20" } ] }</p>';
    }

    public function admin_page() {
        ?>
        <form action='options.php' method='post'>
            <h1>Affiliate Deal Tracker Settings</h1>
            <?php
            settings_fields('adt_settings_group');
            do_settings_sections('affiliate_deal_tracker');
            submit_button();
            ?>
        </form>
        <?php
    }

    private function get_active_deals() {
        $json = get_option($this->option_name, '{}');
        $data = json_decode($json, true);
        if (!isset($data['deals']) || !is_array($data['deals'])) return [];
        $today = date('Y-m-d');
        $active = [];
        foreach ($data['deals'] as $deal) {
            if (isset($deal['expiration_date']) && $deal['expiration_date'] >= $today) {
                $active[] = $deal;
            }
        }
        return $active;
    }

    public function shortcode_display_deals($atts) {
        $deals = $this->get_active_deals();
        if (empty($deals)) return '<p>No active affiliate deals at the moment.</p>';

        $output = '<div class="adt-deal-list">';
        foreach ($deals as $deal) {
            $title = esc_html($deal['title']);
            $desc = esc_html($deal['description']);
            $url = esc_url($deal['affiliate_url']);
            $coupon = isset($deal['coupon_code']) ? esc_html($deal['coupon_code']) : '';
            $exp = esc_html($deal['expiration_date']);

            $output .= '<div class="adt-deal">';
            $output .= '<h3 class="adt-title"><a href="' . $url . '" target="_blank" rel="nofollow noopener noreferrer">' . $title . '</a></h3>';
            $output .= '<p class="adt-desc">' . $desc . '</p>';
            if ($coupon) {
                $output .= '<p class="adt-coupon">Coupon Code: <strong>' . $coupon . '</strong></p>';
            }
            $output .= '<p class="adt-expiration">Expires: ' . $exp . '</p>';
            $output .= '<p><a class="adt-button" href="' . $url . '" target="_blank" rel="nofollow noopener noreferrer">Grab Deal</a></p>';
            $output .= '</div>';
        }
        $output .= '</div>';

        return $output;
    }
}

new AffiliateDealTracker();

// Minimal CSS embedded for basic styling
add_action('wp_head', function() {
    echo '<style>.adt-deal-list{display:flex; flex-wrap:wrap; gap:15px;}.adt-deal{border:1px solid #ddd;padding:15px;flex:1 1 300px; border-radius:6px; background:#f9f9f9;}.adt-title a{color:#21759b; text-decoration:none;}.adt-title a:hover{text-decoration:underline;}.adt-button{display:inline-block;padding:8px 12px;background:#21759b;color:#fff;border-radius:4px;text-decoration:none;font-weight:bold;}.adt-button:hover{background:#125d7e;}.adt-coupon strong{color:#d64646;}</style>';
});