/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Smart_Affiliate_Deal_Booster.php
*/
<?php
/**
 * Plugin Name: Smart Affiliate Deal Booster
 * Description: Auto-display relevant affiliate coupons and deals tailored to your content, boosting affiliate revenue.
 * Version: 1.0
 * Author: Generated by AI
 * License: GPL2
 */

if (!defined('ABSPATH')) {
    exit;
}

class SmartAffiliateDealBooster {
    private $option_key = 'sf_affiliate_deals';

    public function __construct() {
        add_action('admin_menu', array($this, 'admin_menu'));
        add_action('admin_init', array($this, 'settings_init'));
        add_shortcode('smart_affiliate_deals', array($this, 'display_deals_shortcode'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('wp_ajax_sf_fetch_deals', array($this, 'ajax_fetch_deals'));
        add_action('wp_ajax_nopriv_sf_fetch_deals', array($this, 'ajax_fetch_deals'));
    }

    public function admin_menu() {
        add_options_page(
            'Smart Affiliate Deal Booster',
            'Affiliate Deal Booster',
            'manage_options',
            'sf-affiliate-deal-booster',
            array($this, 'options_page')
        );
    }

    public function settings_init() {
        register_setting('sf_affiliate_deal_booster_settings', $this->option_key);

        add_settings_section(
            'sf_section',
            'Plugin Settings',
            null,
            'sf_affiliate_deal_booster_settings'
        );

        add_settings_field(
            'sf_api_key',
            'Affiliate API Key',
            array($this, 'api_key_render'),
            'sf_affiliate_deal_booster_settings',
            'sf_section'
        );

        add_settings_field(
            'sf_max_deals',
            'Maximum Number of Deals to Show',
            array($this, 'max_deals_render'),
            'sf_affiliate_deal_booster_settings',
            'sf_section'
        );

        add_settings_field(
            'sf_exclude_categories',
            'Exclude Categories (comma-separated slugs)',
            array($this, 'exclude_categories_render'),
            'sf_affiliate_deal_booster_settings',
            'sf_section'
        );
    }

    public function api_key_render() {
        $options = get_option($this->option_key);
        ?>
        <input type="text" name="<?php echo esc_attr($this->option_key); ?>[api_key]" value="<?php echo isset($options['api_key']) ? esc_attr($options['api_key']) : ''; ?>" size="40">
        <p class="description">Enter your affiliate network API key to fetch deals (optional, will use public deals without key).</p>
        <?php
    }

    public function max_deals_render() {
        $options = get_option($this->option_key);
        $val = isset($options['max_deals']) ? intval($options['max_deals']) : 5;
        ?>
        <input type="number" name="<?php echo esc_attr($this->option_key); ?>[max_deals]" value="<?php echo $val; ?>" min="1" max="20">
        <p class="description">Maximum number of deals to display in the shortcode output.</p>
        <?php
    }

    public function exclude_categories_render() {
        $options = get_option($this->option_key);
        ?>
        <input type="text" name="<?php echo esc_attr($this->option_key); ?>[exclude_categories]" value="<?php echo isset($options['exclude_categories']) ? esc_attr($options['exclude_categories']) : ''; ?>" size="50">
        <p class="description">Comma-separated category slugs where the deals should not display.</p>
        <?php
    }

    public function options_page() {
        ?>
        <div class="wrap">
            <h1>Smart Affiliate Deal Booster Settings</h1>
            <form action="options.php" method="post">
                <?php
                settings_fields('sf_affiliate_deal_booster_settings');
                do_settings_sections('sf_affiliate_deal_booster_settings');
                submit_button();
                ?>
            </form>
        </div>
        <?php
    }

    public function enqueue_scripts() {
        if (is_singular() && has_shortcode(get_post()->post_content, 'smart_affiliate_deals')) {
            wp_enqueue_style('sf-affiliate-deals-style', plugins_url('style.css', __FILE__));
            wp_enqueue_script('sf-affiliate-deals-js', plugins_url('script.js', __FILE__), array('jquery'), false, true);
            wp_localize_script('sf-affiliate-deals-js', 'sf_ajax', array(
                'ajax_url' => admin_url('admin-ajax.php'),
                'post_id' => get_the_ID()
            ));
        }
    }

    public function display_deals_shortcode($atts) {
        $options = get_option($this->option_key);
        $max_deals = isset($options['max_deals']) ? intval($options['max_deals']) : 5;

        $post_id = get_the_ID();
        $category = get_the_category($post_id);
        $excluded = isset($options['exclude_categories']) ? array_map('trim', explode(',', $options['exclude_categories'])) : array();

        if ($category) {
            foreach ($category as $cat) {
                if (in_array($cat->slug, $excluded)) {
                    return '<p>Deals are hidden in this category.</p>';
                }
            }
        }

        $deals = $this->fetch_deals_for_post($post_id, $max_deals);

        if (empty($deals)) {
            return '<p>No relevant deals found at this time.</p>';
        }

        ob_start();
        echo '<div class="sf-affiliate-deals">';
        echo '<h3>Exclusive Deals & Coupons</h3>';
        echo '<ul>';
        foreach ($deals as $deal) {
            $title = esc_html($deal['title']);
            $url = esc_url($deal['url']);
            $desc = esc_html($deal['description']);
            echo "<li><a href='$url' target='_blank' rel='nofollow noopener'>$title</a>: $desc</li>";
        }
        echo '</ul>';
        echo '</div>';

        return ob_get_clean();
    }

    private function fetch_deals_for_post($post_id, $max) {
        // Simulated data for demo; in real plugin, integrate with affiliate APIs or RSS feeds

        $post = get_post($post_id);

        $keywords = $this->extract_keywords($post->post_title . ' ' . $post->post_content);

        $all_deals = $this->sample_deals();

        $filtered = array();

        foreach ($all_deals as $deal) {
            foreach ($keywords as $keyword) {
                if (stripos($deal['title'], $keyword) !== false || stripos($deal['description'], $keyword) !== false) {
                    $filtered[] = $deal;
                    break;
                }
            }
            if (count($filtered) >= $max) break;
        }

        if (count($filtered) < $max) {
            // Append general deals if not enough filtered
            foreach ($all_deals as $deal) {
                if (!in_array($deal, $filtered)) {
                    $filtered[] = $deal;
                    if (count($filtered) >= $max) break;
                }
            }
        }

        return $filtered;
    }

    private function extract_keywords($text) {
        // Simple keyword extraction: remove stopwords and return unique words longer than 3 letters

        $stopwords = array('the','and','for','with','from','this','that','your','you','have','are','but','not','all','any','can','our','may','will','one','use','more','also','such');
        $text = strtolower($text);
        $words = preg_split('/\W+/', $text);
        $words = array_filter($words, function($w) use ($stopwords) {
            return strlen($w) > 3 && !in_array($w, $stopwords);
        });
        return array_unique($words);
    }

    private function sample_deals() {
        return array(
            array(
                'title' => '30% Off on Premium SEO Tool',
                'url' => 'https://affiliate.example.com/seo-tool?ref=smartboost',
                'description' => 'Boost your site with the best SEO optimization software at a fraction of the price.'
            ),
            array(
                'title' => 'Exclusive 20% Discount on WordPress Hosting',
                'url' => 'https://affiliate.example.com/wp-hosting?ref=smartboost',
                'description' => 'Reliable, fast, and secure hosting tailored for WordPress sites.'
            ),
            array(
                'title' => 'Buy One Get One Free Theme Deal',
                'url' => 'https://affiliate.example.com/themes offer?ref=smartboost',
                'description' => 'Limited time offer on popular premium WordPress themes.'
            ),
            array(
                'title' => 'Save 25% on Online Marketing Courses',
                'url' => 'https://affiliate.example.com/marketing-courses?ref=smartboost',
                'description' => 'Learn marketing secrets from experts and grow your business fast.'
            ),
            array(
                'title' => 'Half Price on Email Marketing Software',
                'url' => 'https://affiliate.example.com/email-marketing?ref=smartboost',
                'description' => 'Automate and personalize your campaigns with ease.'
            )
        );
    }

    public function ajax_fetch_deals() {
        // Placeholder for ajax calls if extended in future
        wp_send_json_error('Not implemented');
    }
}

new SmartAffiliateDealBooster();
