/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Smart_Deal_Aggregator.php
*/
<?php
/**
 * Plugin Name: Smart Deal Aggregator
 * Description: Automatically curates and displays niche-specific deals with affiliate tracking.
 * Version: 1.0
 * Author: Generated by AI
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

class SmartDealAggregator {

    private $option_name = 'sda_settings';

    public function __construct() {
        add_action('admin_menu', [$this, 'add_admin_menu']);
        add_action('admin_init', [$this, 'settings_init']);
        add_shortcode('smart_deals', [$this, 'render_deals_shortcode']);
        add_action('wp_enqueue_scripts', [$this, 'enqueue_scripts']);
    }

    public function add_admin_menu() {
        add_options_page('Smart Deal Aggregator', 'Smart Deal Aggregator', 'manage_options', 'smart_deal_aggregator', [$this, 'options_page']);
    }

    public function settings_init() {
        register_setting('sda', $this->option_name);

        add_settings_section(
            'sda_section',
            __('API and Affiliate Settings', 'sda'),
            null,
            'sda'
        );

        add_settings_field(
            'sda_affiliate_id',
            __('Affiliate ID', 'sda'),
            [$this, 'affiliate_id_render'],
            'sda',
            'sda_section'
        );

        add_settings_field(
            'sda_keywords',
            __('Niche Keywords (comma separated)', 'sda'),
            [$this, 'keywords_render'],
            'sda',
            'sda_section'
        );

        add_settings_field(
            'sda_num_deals',
            __('Number of Deals to Show', 'sda'),
            [$this, 'num_deals_render'],
            'sda',
            'sda_section'
        );
    }

    public function affiliate_id_render() {
        $options = get_option($this->option_name);
        ?>
        <input type='text' name='<?php echo $this->option_name; ?>[affiliate_id]' value='<?php echo isset($options['affiliate_id']) ? esc_attr($options['affiliate_id']) : ''; ?>' placeholder='e.g., AFFILIATE123'>
        <?php
    }

    public function keywords_render() {
        $options = get_option($this->option_name);
        ?>
        <input type='text' size='50' name='<?php echo $this->option_name; ?>[keywords]' value='<?php echo isset($options['keywords']) ? esc_attr($options['keywords']) : ''; ?>' placeholder='e.g., laptops, smartphones, gadgets'>
        <p class='description'>Enter comma separated keywords for deal searches.</p>
        <?php
    }

    public function num_deals_render() {
        $options = get_option($this->option_name);
        $num = isset($options['num_deals']) ? intval($options['num_deals']) : 5;
        ?>
        <input type='number' min='1' max='20' name='<?php echo $this->option_name; ?>[num_deals]' value='<?php echo $num; ?>'>
        <?php
    }

    public function options_page() {
        ?>
        <form action='options.php' method='post'>
            <h2>Smart Deal Aggregator Settings</h2>
            <?php
            settings_fields('sda');
            do_settings_sections('sda');
            submit_button();
            ?>
        </form>
        <?php
    }

    public function enqueue_scripts() {
        wp_enqueue_style('sda_style', plugin_dir_url(__FILE__) . 'style.css');
    }

    private function fetch_deals($keywords, $limit) {
        // Simulated API fetch: In production, replace with real affiliate APIs like Amazon, eBay, etc.
        $keywords_array = array_map('trim', explode(',', $keywords));
        $deals = [];
        $sample_deals = [
            [
                'title' => '50% Off Laptop XYZ',
                'description' => 'High performance laptop with latest features.',
                'url' => 'https://example.com/deal/laptopxyz?aff=' . urlencode($this->get_affiliate_id()),
                'price' => '$799',
                'expiry' => '2026-01-31'
            ],
            [
                'title' => 'Smartphone ABC Discount',
                'description' => 'Latest smartphone with 5G capabilities.',
                'url' => 'https://example.com/deal/smartphoneabc?aff=' . urlencode($this->get_affiliate_id()),
                'price' => '$499',
                'expiry' => '2026-02-15'
            ],
            [
                'title' => 'Wireless Headphones Offer',
                'description' => 'Noise-cancelling wireless headphones on sale.',
                'url' => 'https://example.com/deal/wirelessheadphones?aff=' . urlencode($this->get_affiliate_id()),
                'price' => '$149',
                'expiry' => '2026-01-20'
            ]
        ];

        // Filter deals by keywords, simple simulation
        foreach ($sample_deals as $deal) {
            foreach ($keywords_array as $keyword) {
                if (stripos($deal['title'], $keyword) !== false || stripos($deal['description'], $keyword) !== false) {
                    $deals[] = $deal;
                    break;
                }
            }
            if (count($deals) >= $limit) {
                break;
            }
        }

        return $deals;
    }

    private function get_affiliate_id() {
        $options = get_option($this->option_name);
        return isset($options['affiliate_id']) ? sanitize_text_field($options['affiliate_id']) : '';
    }

    public function render_deals_shortcode() {
        $options = get_option($this->option_name);
        if (empty($options) || empty($options['keywords'])) {
            return '<p>Please configure Smart Deal Aggregator with keywords and affiliate ID in plugin settings.</p>';
        }

        $keywords = $options['keywords'];
        $num_deals = isset($options['num_deals']) ? intval($options['num_deals']) : 5;
        $deals = $this->fetch_deals($keywords, $num_deals);

        if (empty($deals)) {
            return '<p>No deals found for your selected keywords.</p>';
        }

        $html = '<div class="sda-deals"><ul>';
        foreach ($deals as $deal) {
            $html .= '<li class="sda-deal-item">';
            $html .= '<a href="' . esc_url($deal['url']) . '" target="_blank" rel="nofollow noopener">';
            $html .= '<strong>' . esc_html($deal['title']) . '</strong> - ' . esc_html($deal['price']) . '</a>';
            $html .= '<p>' . esc_html($deal['description']) . '</p>';
            $html .= '<small>Expires on: ' . esc_html($deal['expiry']) . '</small>';
            $html .= '</li>';
        }
        $html .= '</ul></div>';

        return $html;
    }
}

new SmartDealAggregator();