/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Smart_Affiliate_Coupons_Pro.php
*/
<?php
/**
 * Plugin Name: Smart Affiliate Coupons Pro
 * Plugin URI: https://example.com/smart-affiliate-coupons
 * Description: Automatically generates and displays personalized affiliate coupon codes with tracking to boost conversions.
 * Version: 1.0.0
 * Author: Your Name
 * License: GPL v2 or later
 * Text Domain: smart-affiliate-coupons
 */

if (!defined('ABSPATH')) {
    exit;
}

class SmartAffiliateCoupons {
    private static $instance = null;

    public static function get_instance() {
        if (null === self::$instance) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        add_action('init', array($this, 'init'));
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
        add_action('admin_menu', array($this, 'admin_menu'));
        add_action('wp_ajax_save_coupon', array($this, 'ajax_save_coupon'));
        add_shortcode('sac_coupon', array($this, 'coupon_shortcode'));
        register_activation_hook(__FILE__, array($this, 'activate'));
    }

    public function init() {
        load_plugin_textdomain('smart-affiliate-coupons', false, dirname(plugin_basename(__FILE__)) . '/languages');
    }

    public function enqueue_scripts() {
        wp_enqueue_script('sac-script', plugin_dir_url(__FILE__) . 'sac-script.js', array('jquery'), '1.0.0', true);
        wp_localize_script('sac-script', 'sac_ajax', array('ajax_url' => admin_url('admin-ajax.php'), 'nonce' => wp_create_nonce('sac_nonce')));
        wp_enqueue_style('sac-style', plugin_dir_url(__FILE__) . 'sac-style.css', array(), '1.0.0');
    }

    public function admin_menu() {
        add_options_page('Smart Affiliate Coupons', 'SAC Pro', 'manage_options', 'smart-affiliate-coupons', array($this, 'admin_page'));
    }

    public function admin_page() {
        if (isset($_POST['sac_save'])) {
            update_option('sac_coupons', sanitize_textarea_field($_POST['coupons']));
            echo '<div class="notice notice-success"><p>Coupons saved!</p></div>';
        }
        $coupons = get_option('sac_coupons', "Brand1|DISCOUNT10|https://affiliate.link1\nBrand2|SAVE20|https://affiliate.link2");
        ?>
        <div class="wrap">
            <h1>Smart Affiliate Coupons Settings</h1>
            <form method="post">
                <p><label>Coupons (format: Brand|Code|Affiliate URL, one per line):</label></p>
                <textarea name="coupons" rows="10" cols="80"><?php echo esc_textarea($coupons); ?></textarea>
                <p class="submit"><input type="submit" name="sac_save" class="button-primary" value="Save Coupons"></p>
            </form>
            <p>Use shortcode <code>[sac_coupon]</code> to display coupons. Pro version unlocks analytics and auto-generation.</p>
        </div>
        <?php
    }

    public function ajax_save_coupon() {
        check_ajax_referer('sac_nonce', 'nonce');
        if (current_user_can('manage_options')) {
            $coupon = sanitize_text_field($_POST['coupon']);
            $coupons = get_option('sac_coupons', '') . "\n" . $coupon;
            update_option('sac_coupons', $coupons);
            wp_send_json_success('Coupon saved!');
        }
        wp_send_json_error();
    }

    public function coupon_shortcode($atts) {
        $atts = shortcode_atts(array('id' => ''), $atts);
        $coupons = explode("\n", get_option('sac_coupons', ''));
        $html = '<div class="sac-coupons">';
        foreach ($coupons as $coupon) {
            $parts = explode('|', trim($coupon));
            if (count($parts) === 3) {
                $html .= '<div class="sac-item"><strong>' . esc_html($parts) . '</strong>: <code>' . esc_html($parts[1]) . '</code> <a href="' . esc_url($parts[2]) . '" target="_blank" rel="nofollow">Shop Now</a></div>';
            }
        }
        $html .= '</div><p><em>Generated by Smart Affiliate Coupons Pro. <a href="' . admin_url('options-general.php?page=smart-affiliate-coupons') . '">Manage</a></em></p>';
        return $html;
    }

    public function activate() {
        if (!get_option('sac_coupons')) {
            update_option('sac_coupons', "Brand1|DISCOUNT10|https://youraffiliatelink1.com\nBrand2|SAVE20|https://youraffiliatelink2.com");
        }
    }
}

SmartAffiliateCoupons::get_instance();

// Pro Upsell Notice
function sac_pro_notice() {
    if (!current_user_can('manage_options')) return;
    echo '<div class="notice notice-info"><p>Unlock <strong>Smart Affiliate Coupons Pro</strong>: Advanced tracking, unlimited coupons, and analytics for $49/year! <a href="https://example.com/pro" target="_blank">Upgrade Now</a></p></div>';
}
add_action('admin_notices', 'sac_pro_notice');

// Minimal CSS
/*
.sac-coupons { background: #f9f9f9; padding: 20px; border: 1px solid #ddd; border-radius: 5px; }
.sac-item { margin-bottom: 10px; padding: 10px; background: white; border-left: 4px solid #0073aa; }
*/
// Save as sac-style.css in plugin folder

// Minimal JS
/*
jQuery(document).ready(function($) {
    // Add coupon form if needed
});
*/
// Save as sac-script.js in plugin folder
?>