/*
Author: Auto Plugin Factory
Author URI: https://automation.bhandarum.in/generated-plugins/tracker.php?plugin=Content_Monetizer_Pro.php
*/
<?php
/**
 * Plugin Name: Content Monetizer Pro
 * Description: Monetize your WordPress site with subscriptions, affiliate marketing, and targeted ads.
 * Version: 1.0
 * Author: Generated by AI
 * License: GPL2
 */

if ( !defined('ABSPATH') ) exit;

class ContentMonetizerPro {
    public function __construct() {
        add_action('admin_menu', array($this, 'cmp_admin_menu'));
        add_action('admin_init', array($this, 'cmp_settings_init'));
        add_shortcode('cmp_subscribe_form', array($this, 'cmp_subscribe_form_shortcode'));
        add_action('wp_enqueue_scripts', array($this, 'cmp_enqueue_scripts'));
        add_filter('the_content', array($this, 'cmp_display_ads'));
        add_action('wp_ajax_cmp_subscribe', array($this, 'cmp_handle_subscription'));
        add_action('wp_ajax_nopriv_cmp_subscribe', array($this, 'cmp_handle_subscription'));
    }

    public function cmp_admin_menu() {
        add_menu_page('Content Monetizer', 'Content Monetizer', 'manage_options', 'cmp_settings', array($this, 'cmp_settings_page'), 'dashicons-money-alt');
    }

    public function cmp_settings_init() {
        register_setting('cmp_settings_group', 'cmp_settings');
        add_settings_section('cmp_main_section', 'Main Settings', null, 'cmp_settings');

        add_settings_field('cmp_affiliate_id', 'Affiliate ID', array($this, 'cmp_text_field_render'), 'cmp_settings', 'cmp_main_section', ['label_for' => 'cmp_affiliate_id']);

        add_settings_field('cmp_ad_code', 'Ad Code', array($this, 'cmp_textarea_field_render'), 'cmp_settings', 'cmp_main_section', ['label_for' => 'cmp_ad_code']);

        add_settings_field('cmp_subscription_enabled', 'Enable Subscription', array($this, 'cmp_checkbox_field_render'), 'cmp_settings', 'cmp_main_section', ['label_for' => 'cmp_subscription_enabled']);
    }

    public function cmp_text_field_render($args) {
        $options = get_option('cmp_settings');
        ?>
        <input type='text' id='<?php echo esc_attr($args['label_for']); ?>' name='cmp_settings[<?php echo esc_attr($args['label_for']); ?>]' value='<?php echo isset($options[$args['label_for']]) ? esc_attr($options[$args['label_for']]) : ''; ?>' style='width: 300px;'>
        <?php
    }

    public function cmp_textarea_field_render($args) {
        $options = get_option('cmp_settings');
        ?>
        <textarea id='<?php echo esc_attr($args['label_for']); ?>' name='cmp_settings[<?php echo esc_attr($args['label_for']); ?>]' rows='5' style='width: 300px;'><?php echo isset($options[$args['label_for']]) ? esc_textarea($options[$args['label_for']]) : ''; ?></textarea>
        <?php
    }

    public function cmp_checkbox_field_render($args) {
        $options = get_option('cmp_settings');
        ?>
        <input type='checkbox' id='<?php echo esc_attr($args['label_for']); ?>' name='cmp_settings[<?php echo esc_attr($args['label_for']); ?>]' value='1' <?php checked(1, isset($options[$args['label_for']]) ? $options[$args['label_for']] : 0); ?>>
        <?php
    }

    public function cmp_settings_page() {
        ?>
        <div class='wrap'>
            <h1>Content Monetizer Pro Settings</h1>
            <form action='options.php' method='post'>
                <?php
                settings_fields('cmp_settings_group');
                do_settings_sections('cmp_settings');
                submit_button();
                ?>
            </form>
        </div>
        <?php
    }

    public function cmp_subscribe_form_shortcode() {
        if (!is_user_logged_in()) {
            ob_start();
            ?>
            <form id='cmp-subscribe-form'>
                <label for='cmp-email'>Email:</label><br>
                <input type='email' id='cmp-email' name='email' required><br><br>
                <input type='submit' value='Subscribe'>
                <div id='cmp-subscribe-message'></div>
            </form>
            <script>
            document.getElementById('cmp-subscribe-form').addEventListener('submit', function(e) {
                e.preventDefault();
                var email = document.getElementById('cmp-email').value;
                var data = new FormData();
                data.append('action', 'cmp_subscribe');
                data.append('email', email);
                fetch('<?php echo admin_url('admin-ajax.php'); ?>', {
                    method: 'POST',
                    credentials: 'same-origin',
                    body: data
                }).then(response => response.json()).then(response => {
                    document.getElementById('cmp-subscribe-message').innerText = response.message;
                });
            });
            </script>
            <?php
            return ob_get_clean();
        } else {
            return '<p>You are already subscribed.</p>';
        }
    }

    public function cmp_handle_subscription() {
        $email = isset($_POST['email']) ? sanitize_email($_POST['email']) : '';
        if (!is_email($email)) {
            wp_send_json(['success' => false, 'message' => 'Invalid email address.']);
        }
        $subscribers = get_option('cmp_subscribers', []);
        if (in_array($email, $subscribers)) {
            wp_send_json(['success' => false, 'message' => 'Email already subscribed.']);
        } else {
            $subscribers[] = $email;
            update_option('cmp_subscribers', $subscribers);
            wp_send_json(['success' => true, 'message' => 'Thank you for subscribing!']);
        }
    }

    public function cmp_enqueue_scripts() {
        // Add any front-end scripts or styles here
    }

    public function cmp_display_ads($content) {
        $options = get_option('cmp_settings');
        if (!empty($options['cmp_ad_code'])) {
            $ad_code = $options['cmp_ad_code'];
            return $content . "<div class='cmp-ad-container'>" . $ad_code . "</div>";
        }
        return $content;
    }
}

new ContentMonetizerPro();
